### ISSUE TITLE
MP4 Muxer duration not correct

### ISSUE THREAD

**Issue by cedricve** [yapingcat/gomedia#106]
Hey great work,

I'm decoding an RTSP stream, and trying to write to an mp4 using your MP4 muxer. I can start writing the H264 packets to the stream, but when I try to play to video it shows a huge total duration and it doesn't play the video. Any thoughts? I was thinking about the dts value being incoorect.

![Screenshot 2023-11-29 at 17 13 31](https://github.com/yapingcat/gomedia/assets/1546779/da22a52e-2172-4deb-85c4-45fc98cd4ac3)

Find a recording here:

https://github.com/yapingcat/gomedia/assets/1546779/5fc1ff06-8235-4936-a74b-dda8fbab65b1

I did do an MP4 parse, and got this returned. Not sure if the muxer (and how) it is calculating the framerate.

![Screenshot 2023-11-29 at 17 21 27](https://github.com/yapingcat/gomedia/assets/1546779/047a3254-7b1a-4a44-98f0-7fee94b723a6)

**Comment by 3052** [comment]
can you give more info? I am having the same problem

**Comment by cedricve** [comment]
you should provide the correct DTS value, most of the time DTS = PTS. That fixed my issue.

**Comment by 3052** [comment]
sorry I dont know what you're talking about. my code is similar to this:

https://github.com/yapingcat/gomedia/blob/main/example/example_demux_fmp4.go
