### ISSUE TITLE
网站在正常视频的ts列表中加入了几个ts广告，使用gomedia合并正常视频、广告就会出现最终输出结果无法播放的情况

### ISSUE THREAD

**Issue by orestonce** [yapingcat/gomedia#124]
[合并错误.zip](https://github.com/yapingcat/gomedia/files/14610423/default.zip)
问题来源: https://github.com/orestonce/m3u8d/issues/29

- 广告的ts列表是 572~575，广告没有声音
- 直接点击广告的ts是可以播放的
- 直接点击视频的ts是可以播放的, 视频有声音
- ffmpeg和gomedia合并广告 572~575，都可以播放
- ffmpeg和gomedia合并原始视频和广告，都无法播放
  - 使用ffmpeg 合并mp4也无法播放，我使用的命令是: 
   `ffmpeg -i "concat:00571.ts|00572.ts|00573.ts|00574.ts|00575.ts|00576.ts" -c copy output.mp4`

**Comment by yapingcat** [comment]
合成的视频 ffplay 可以播放。
这个视频宽高不一致，播放需要重置解码器，有些播放不一定能支持

**Comment by yapingcat** [comment]
gomedia 不会把pps id 和sps id 相同的sps/pps 写入到mp4中,所以导致了和ffmpeg之间存在差异

**Comment by orestonce** [comment]
目前gomedia，可以解析出ts的中的视频长宽吗？

**Comment by yapingcat** [comment]
> 目前gomedia，可以解析出ts的中的视频长宽吗？

可以的，用下面这个function就可以,
https://github.com/yapingcat/gomedia/blob/1b855b02fa0d0b53d2ca9d9a1382ce08914905bd/go-codec/h264.go#L235

**Comment by yapingcat** [comment]
可以参考下面的代码
```golang
 demuxer := mpeg2.NewTSDemuxer()
	demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
		if cid == mpeg2.TS_STREAM_H264 {
			codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
				if codec.H264NaluType(nalu) == codec.H264_NAL_SPS {
					w, h := codec.GetH264Resolution(nalu)
					fmt.Println(w, h)
					return true
				}
				return false
			})

		}
	}
```

**Comment by orestonce** [comment]
好，刚才正好看见实验了一下，可以解析出对应ts的宽高

**Comment by orestonce** [comment]
还有一个想法，能不能将解析出来的帧数据对应视频的画面重新调整大小呢？

**Comment by yapingcat** [comment]
> 还有一个想法，能不能将解析出来的帧数据对应视频的画面重新调整大小呢？

改变宽高一般要用ffmpeg  scale 这个filter
如果仅仅想改变播放出来的画面的宽高比，可以修改sar/dar

**Comment by orestonce** [comment]
## 非常感谢你提供的思路
* 最终使用 "把 EXT-X-DISCONTINUITY 之间的分片过滤掉" 的方式解决了此问题
