### ISSUE TITLE
Example to convert mp4 to TS

### ISSUE THREAD

**Issue by magicbic** [yapingcat/gomedia#125]
Hello, @yapingcat!

First, I would like to thank you for taking the time to write this robust and useful library to manipulate media files using Go. I've read your example files and I believe I have a use case that is does not have an example to follow along.

My use case is to convert mp4 files into mpeg-ts on the fly before deliverying them to customers.

I have been trying to play along with this example:
https://github.com/yapingcat/gomedia/blob/main/example/example_play_mp4_with_hls.go

It works with vod content in .mp4 and does converts the its content to mpeg-ts and it plays fine on different devices.

Would you be kind to share or include a new example converting fragmented .mp4 files to ts?

**Comment by magicbic** [comment]
I forgot to mention that my .mp4 files does not containg `stss box`. Which I believe is a requirement for you library to parse the info inside the .mp4 to generate the mpegts.

What I am trying to achieve here is similar to this ffmpeg command:

```
ffmpeg -i input.mp4 -c copy output.ts
```

**Comment by yapingcat** [comment]
```golang
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/yapingcat/gomedia/go-mp4"
	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {

	mp4filename := os.Args[1]

	f, err := os.Open(mp4filename)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()
	demuxer := mp4.CreateMp4Demuxer(f)
	if infos, err := demuxer.ReadHead(); err != nil && err != io.EOF {
		fmt.Println(err)
	} else {
		fmt.Printf("%+v\n", infos)
	}
	tsFile, _ := os.OpenFile(os.Args[2], os.O_CREATE|os.O_RDWR, 0666)
	defer tsFile.Close()
	ts := mpeg2.NewTSMuxer()
	vid := ts.AddStream(mpeg2.TS_STREAM_H264)
	aid := ts.AddStream(mpeg2.TS_STREAM_AAC)

	for {
		pkg, err := demuxer.ReadPacket()
		if err != nil {
			fmt.Println(err)
			break
		}
		fmt.Printf("track:%d,cid:%+v,pts:%d dts:%d\n", pkg.TrackId, pkg.Cid, pkg.Pts, pkg.Dts)
		if pkg.Cid == mp4.MP4_CODEC_H264 {
			ts.Write(vid, pkg.Data, pkg.Pts, pkg.Dts)
		} else if pkg.Cid == mp4.MP4_CODEC_AAC {
			ts.Write(aid, pkg.Data, pkg.Pts, pkg.Dts)
		}
	}
}
```

“ converting fragmented .mp4 files to ts” is the same as this code

**Comment by magicbic** [comment]
@yapingcat Thank you for your quick response! I've tried similar approach and different variations, but all I got was a HLS with a freezed frame.

Now with your exemple it is much clearer to me what I should have done in the first. One thing that I missed in your example is this call:
```go
ts.OnPacket = func(pkg []byte) {
		buf.Write(pkg)
	}
```

This way I can write to my buffer as I loop through packages.

Thank you so much again for this outstanding library!

**Comment by yapingcat** [comment]
> @yapingcat Thank you for your quick response! I've tried similar approach and different variations, but all I got was a HLS with a freezed frame.
> 
> Now with your exemple it is much clearer to me what I should have done in the first place. One thing that I missed in your example is this call:
> 
> ```go
> ts.OnPacket = func(pkg []byte) {
> 		buf.Write(pkg)
> 	}
> ```
> 
> This way I can write to my buffer as I loop through packages. Now it works!
> 
> Thank you so much again for this outstanding library!
