### ISSUE TITLE
merge two mp4 files into ts.

### ISSUE THREAD

**Issue by magicbic** [yapingcat/gomedia#126]
I have this portion of code to merge two mp4 files into one TS. I have video and audio separated and want to have them on single file.

```go
func convertToTs(video []byte, audio []byte) ([]byte, error) {
	v := bytes.NewReader(video)
	vDemuxer := mp4.CreateMp4Demuxer(v)
	vInfos, err := vDemuxer.ReadHead()
	if err != nil && err != io.EOF {
		m.l.Warn("Failed to read head", "err", err)
		return nil, err
	}

	a := bytes.NewReader(audio)
	aDemuxer := mp4.CreateMp4Demuxer(a)
	aInfos, err := aDemuxer.ReadHead()
	if err != nil && err != io.EOF {
		m.l.Warn("Failed to read head", "err", err)
		return nil, err
	}

	buf := new(bytes.Buffer)
	ts := mpeg2.NewTSMuxer()
	ts.OnPacket = func(pkg []byte) {
		buf.Write(pkg)
	}
	vCodec := vInfos[0].Cid
	aCodec := aInfos[0].Cid

	var vStream, aStream uint16

	switch vCodec {
	case mp4.MP4_CODEC_H265:
		vStream = ts.AddStream(mpeg2.TS_STREAM_H265)
	case mp4.MP4_CODEC_H264:
		vStream = ts.AddStream(mpeg2.TS_STREAM_H264)
	}

	switch aCodec {
	case mp4.MP4_CODEC_AAC:
		aStream = ts.AddStream(mpeg2.TS_STREAM_AAC)
	}

	for {
		pkg, err := vDemuxer.ReadPacket()
		if err != nil && err != io.EOF {
			m.l.Warn("Failed to read packet", "err", err)
		}
		if err == io.EOF {
			break
		}

		switch pkg.Cid {
		case mp4.MP4_CODEC_H265:
			ts.Write(vStream, pkg.Data, pkg.Pts, pkg.Dts)
		case mp4.MP4_CODEC_H264:
			ts.Write(vStream, pkg.Data, pkg.Pts, pkg.Dts)
		}
	}

	for {
		pkg, err := aDemuxer.ReadPacket()
		if err != nil && err != io.EOF {
			m.l.Warn("Failed to read packet", "err", err)
		}
		if err == io.EOF {
			break
		}

		switch pkg.Cid {

		case mp4.MP4_CODEC_AAC:
			ts.Write(aStream, pkg.Data, pkg.Pts, pkg.Dts)
		}
	}

	return buf.Bytes(), nil
}
```

I can play the stream via VLC but no audio. The same happens if I try to ingest it with FFMPEG, it only shows on media information that the tracks available is video.

What am I possibly doing wrong in this case?

**Comment by magicbic** [comment]
If I use this extension https://chromewebstore.google.com/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof

The stream does play with video and audio. I just wonder why I can replicate with VLC and FFMPEG.

Is there an e-mail where I can contact you?

**Comment by yapingcat** [comment]
you should write video and audio frame alternately.

**Comment by yapingcat** [comment]
please show your ffmpeg commad that you use to merge file

**Comment by magicbic** [comment]
I am not using ffmpeg to merge the files. They come as separate mp4 files that’s why I have written this portion of code to have a final TS file containing both streams of video and audio.

**Comment by yapingcat** [comment]
please refer to this pseudocode

```golang
var v_pkg *AVPacket = nil
var a_pkg *AVPacket = nil
var video_err  error = nil
var audio_err error =nil
for {
        if  v_pkg == nil {
              v_pkg, video_err  = vDemuxer.ReadPacket()
        }

       if a_pkg == nil {
               a_pkg, audio_err = aDemuxer.ReadPacket()	
       }
       if  audio_err  != nil or  video_err != nil {
                 break
      } 

       if  v_pkg.pts < a_pkg.pts {
             ... write video frame into ts file
              v_pkg = nil
       } else {
             ... write audio frame into ts file
            a_pkg = nil 
      }  
}

```

**Comment by magicbic** [comment]
@yapingcat Thanks for the provided piece of code. May I ask what is exactly doing? As of my understanding we are reading packets from video and audio and if the video pts is earlier than audio's pts we write the data to ts as video stream or else we write the data to ts as audio stream.

Could please explain to me why this logic is important to make it work? I haven't tried it yet but I can sense it will work.

**Comment by yapingcat** [comment]
ffmpeg probe the ts file,. in short, ffmpeg  reads part of the data from the beginning to analyze video/audio information.
you can search something about ‘probesize’ ，‘analyzeduration’ in google . probesize and analyzeduration is  ffmpeg command  option to control the probe distance.

in this case , you write  all video frame into ts file before  write audio,so ffmpeg can't detect audio.

**Comment by magicbic** [comment]
It makes so much sense to me now. I am familiar with the ffmpeg input arguments probesize and analyze duration and I see the reason for VLC or FFMPEG to not detect the audio stream.
