### ISSUE TITLE
high ram usage

### ISSUE THREAD

**Issue by jumoog** [yapingcat/gomedia#127]
Thanks for your great work!
I use your [example_convert_ts_to_mp4](https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go) to convert ts files to mp4. Sometimes I have very large ts files that use up all my RAM when converting. And Linux kills my process.
Is there a way to work in chunks?

**Comment by yapingcat** [comment]
https://github.com/yapingcat/gomedia/blob/76660eca7389898cc663e32101b7323a961760cc/go-mpeg2/ts-demuxer.go#L50

io.Reader is the interface. so you can implement 'chunk reader' by yourself.

**Comment by yapingcat** [comment]
i think  **bufio.NewReader()**  is good enough for you

**Comment by yapingcat** [comment]
This question has been discussed in this pr https://github.com/yapingcat/gomedia/pull/9

**Comment by jumoog** [comment]
Thank you!
