### ISSUE TITLE
将mp4解析后 通过rtsp server等待推送。

### ISSUE THREAD

**Issue by YoooDT** [yapingcat/gomedia#152]
大佬，这个有实现嘛，或者说有大概步骤嘛。

**Comment by YoooDT** [comment]
看了下这个issues
https://github.com/yapingcat/gomedia/issues/116
我想实现启动一个rtsp server, 当rtsp client 响应server时，server的视频源时mp4文件

**Comment by yapingcat** [comment]
参考这个例子 https://github.com/yapingcat/gomedia/blob/main/example/example_rtsp_play_server.go

**Comment by yapingcat** [comment]
在 HandleDescribe  使用rtsp.NewVideoTrack() 创建Track，使用rtsp.RTSP_CODEC_H264/rtsp.RTSP_CODEC_H265来创建
如果是udp收发流，就在HandleSetup 设置端口号，tcp就不需要了
最后HandlePlay 开启发流协程

**Comment by YoooDT** [comment]
thanks :)
