### ISSUE TITLE
解码视频文件信息：fps和分辨率

### ISSUE THREAD

**Issue by orestonce** [yapingcat/gomedia#154]
* 目前未找到怎么获取到媒体文件的fps信息的函数，后续能够提供一下吗 ?
* 获取媒体文件分辨率的时候，我发现宽高与ffmpeg输出不一致，gomedia输出都是16x16，ffmpeg输出为1920x1080,具体代码为:
````
w, h := codec.GetH264Resolution(data)
fmt.Println(one.Name(), "resolve", w, h)
````
![捕获](https://github.com/user-attachments/assets/5886feb0-a13a-4403-bd79-b77b7d88688c)

使用的ts文件:
[1-120.zip](https://github.com/user-attachments/files/17036558/1-120.zip)

**Comment by yapingcat** [comment]
我这边测试分辨率是可以正确获取的

```golang
demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
		if cid == mpeg2.TS_STREAM_H264 {
			codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
				naluType := codec.H264NaluType(nalu)
				if naluType == codec.H264_NAL_SPS {
					fmt.Println(codec.GetH264Resolution(nalu))
                                         return false
				}
				fmt.Println("naluType", naluType, "pts:", pts, "dts:", dts, "size:", len(nalu))
				return true
			})
	}
```

**Comment by orestonce** [comment]
哦，那是个误会，我以为 codec.GetH264Resolution 的参数是ts的原始信息。

**Comment by yapingcat** [comment]
当前只能通过解析vui 来获取fps ，但是vui不一定有

**Comment by yapingcat** [comment]
https://stackoverflow.com/questions/31334973/find-frame-rate-sps
目前gomedia 支持解析sps 拿到vui，可以参考下这个文档 计算fps

**Comment by orestonce** [comment]
panic了
````
1920 1080
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/yapingcat/gomedia/go-codec.(*VPS).Decode(0xc0000b78a0, {0xc0003be006?
, 0xc0000b7ab8?, 0x2?})
````
你看看这样写有什么问题:
````go
package main

import (
	"bytes"
	"fmt"
	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-mpeg2"
	"os"
)

func main() {
	demuxer := mpeg2.NewTSDemuxer()
	demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
		if cid == mpeg2.TS_STREAM_H264 {
			codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
				naluType := codec.H264NaluType(nalu)
				if naluType == codec.H264_NAL_SPS {
					fmt.Println(codec.GetH264Resolution(nalu))
					var vps codec.VPS
					vps.Decode(nalu)
					ti := vps.TimeInfo
					fmt.Println("scale", ti.Vps_time_scale, "tick", ti.Vps_num_units_in_tick)
					if ti.Vps_num_units_in_tick > 0 {
						fmt.Println(ti.Vps_time_scale / ti.Vps_num_units_in_tick)
					}
					return false
				}
				//fmt.Println("naluType", naluType, "pts:", pts, "dts:", dts, "size:", len(nalu))
				return true
			})
		}
	}

	data, err := os.ReadFile(`D:\temp\00120.ts`)
	checkErr(err)

	err = demuxer.Input(bytes.NewReader(data))
	checkErr(err)
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
````

**Comment by orestonce** [comment]
改成了以下代码，发现没崩溃了，但是scale和tick都是0

````go
package main

import (
	"bytes"
	"fmt"
	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-mpeg2"
	"os"
)

func main() {
	demuxer := mpeg2.NewTSDemuxer()
	demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
		if cid == mpeg2.TS_STREAM_H264 {
			codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
				naluType := codec.H264NaluType(nalu)
				if naluType == codec.H264_NAL_SPS {
					fmt.Println(codec.GetH264Resolution(nalu))
					start, sc := codec.FindStartCode(nalu, 0)
					nalu = nalu[start+int(sc):]

					var vps codec.VPS
					vps.Decode(nalu)
					ti := vps.TimeInfo
					fmt.Println("scale", ti.Vps_time_scale, "tick", ti.Vps_num_units_in_tick)
					if ti.Vps_num_units_in_tick > 0 {
						fmt.Println(ti.Vps_time_scale / ti.Vps_num_units_in_tick)
					}
					return false
				}
				//fmt.Println("naluType", naluType, "pts:", pts, "dts:", dts, "size:", len(nalu))
				return true
			})
		}
	}

	data, err := os.ReadFile(`D:\temp\00120.ts`)
	checkErr(err)

	err = demuxer.Input(bytes.NewReader(data))
	checkErr(err)
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
````

**Comment by yapingcat** [comment]
> 改成了以下代码，发现没崩溃了，但是scale和tick都是0
> 
> ```go
> package main
> 
> import (
> 	"bytes"
> 	"fmt"
> 	"github.com/yapingcat/gomedia/go-codec"
> 	"github.com/yapingcat/gomedia/go-mpeg2"
> 	"os"
> )
> 
> func main() {
> 	demuxer := mpeg2.NewTSDemuxer()
> 	demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
> 		if cid == mpeg2.TS_STREAM_H264 {
> 			codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
> 				naluType := codec.H264NaluType(nalu)
> 				if naluType == codec.H264_NAL_SPS {
> 					fmt.Println(codec.GetH264Resolution(nalu))
> 					start, sc := codec.FindStartCode(nalu, 0)
> 					nalu = nalu[start+int(sc):]
> 
> 					var vps codec.VPS
> 					vps.Decode(nalu)
> 					ti := vps.TimeInfo
> 					fmt.Println("scale", ti.Vps_time_scale, "tick", ti.Vps_num_units_in_tick)
> 					if ti.Vps_num_units_in_tick > 0 {
> 						fmt.Println(ti.Vps_time_scale / ti.Vps_num_units_in_tick)
> 					}
> 					return false
> 				}
> 				//fmt.Println("naluType", naluType, "pts:", pts, "dts:", dts, "size:", len(nalu))
> 				return true
> 			})
> 		}
> 	}
> 
> 	data, err := os.ReadFile(`D:\temp\00120.ts`)
> 	checkErr(err)
> 
> 	err = demuxer.Input(bytes.NewReader(data))
> 	checkErr(err)
> }
> 
> func checkErr(err error) {
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```

`var sps codec.SPS  ` 用sps 解析

**Comment by yapingcat** [comment]
```golang
if naluType == codec.H264_NAL_SPS {
	w, h := codec.GetH264Resolution(nalu)
	start, sc := codec.FindStartCode(nalu, 0)
	sodb := codec.CovertRbspToSodb(nalu[start+int(sc)+1:])
	bs := codec.NewBitStream(sodb)
	var s codec.SPS
	s.Decode(bs)
	fmt.Println(s.VuiParameters.TimingInfoPresentFlag, s.VuiParameters.FixedFrameRateFlag, s.VuiParameters.TimeScale, s.VuiParameters.NumUnitsInTick)

	fmt.Println(w, h)
}
```

**Comment by orestonce** [comment]
https://github.com/yapingcat/gomedia/issues/154#issuecomment-2361077326 改到了这个版本，数据有了但数据和ffmpeg对不上。
````go
fmt.Println(s.VuiParameters.TimingInfoPresentFlag, s.VuiParameters.FixedFrameRateFlag, s.VuiParameters.TimeScale, s.VuiParameters.NumUnitsInTick)
````

* 00001.ts 在ffmpeg上显示是25fps，gomedia的SPS解析出来是50 ( TimeScale / NumUnitsInTick )
````
>ffmpeg -i 00001.ts
Input #0, mpegts, from '00001.ts':
  Duration: 00:00:06.30, start: 1.456778, bitrate: 866 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x101](und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
At least one output file must be specified

>gomedia
1 0 50 1
1 0 50 1
````
* 00120.ts 在ffmpeg上显示是30fps，gomedia解析出来是60
````
>ffmpeg -i 00120.ts
Input #0, mpegts, from '00120.ts':
  Duration: 00:00:06.71, start: 1.420444, bitrate: 2672 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn

>gomedia
1 0 60 1
1 0 60 1
````

**Comment by yapingcat** [comment]
> [#154 (comment)](https://github.com/yapingcat/gomedia/issues/154#issuecomment-2361077326) 改到了这个版本，数据有了但数据和ffmpeg对不上。
> 
> ```go
> fmt.Println(s.VuiParameters.TimingInfoPresentFlag, s.VuiParameters.FixedFrameRateFlag, s.VuiParameters.TimeScale, s.VuiParameters.NumUnitsInTick)
> ```
> 
> * 00001.ts 在ffmpeg上显示是25fps，gomedia的SPS解析出来是50 ( TimeScale / NumUnitsInTick )
> 
> ```
> >ffmpeg -i 00001.ts
> Input #0, mpegts, from '00001.ts':
>   Duration: 00:00:06.30, start: 1.456778, bitrate: 866 kb/s
>   Program 1
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
>   Stream #0:1[0x101](und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
> At least one output file must be specified
> 
> >gomedia
> 1 0 50 1
> 1 0 50 1
> ```
> 
> * 00120.ts 在ffmpeg上显示是30fps，gomedia解析出来是60
> 
> ```
> >ffmpeg -i 00120.ts
> Input #0, mpegts, from '00120.ts':
>   Duration: 00:00:06.71, start: 1.420444, bitrate: 2672 kb/s
>   Program 1
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn
> 
> >gomedia
> 1 0 60 1
> 1 0 60 1
> ```

https://github.com/rgaufman/live555/blob/2c92a57ca04b83b2038ab2ab701d05a54be06a85/liveMedia/H264or5VideoStreamFramer.cpp#L976

可以参考下live555 实现 264 需要除以2，265不需要

**Comment by yapingcat** [comment]
> [#154 (comment)](https://github.com/yapingcat/gomedia/issues/154#issuecomment-2361077326) 改到了这个版本，数据有了但数据和ffmpeg对不上。
> 
> ```go
> fmt.Println(s.VuiParameters.TimingInfoPresentFlag, s.VuiParameters.FixedFrameRateFlag, s.VuiParameters.TimeScale, s.VuiParameters.NumUnitsInTick)
> ```
> 
> * 00001.ts 在ffmpeg上显示是25fps，gomedia的SPS解析出来是50 ( TimeScale / NumUnitsInTick )
> 
> ```
> >ffmpeg -i 00001.ts
> Input #0, mpegts, from '00001.ts':
>   Duration: 00:00:06.30, start: 1.456778, bitrate: 866 kb/s
>   Program 1
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn
>   Stream #0:1[0x101](und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 131 kb/s
> At least one output file must be specified
> 
> >gomedia
> 1 0 50 1
> 1 0 50 1
> ```
> 
> * 00120.ts 在ffmpeg上显示是30fps，gomedia解析出来是60
> 
> ```
> >ffmpeg -i 00120.ts
> Input #0, mpegts, from '00120.ts':
>   Duration: 00:00:06.71, start: 1.420444, bitrate: 2672 kb/s
>   Program 1
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn
> 
> >gomedia
> 1 0 60 1
> 1 0 60 1
> ```
https://github.com/rgaufman/live555/blob/2c92a57ca04b83b2038ab2ab701d05a54be06a85/liveMedia/H264or5VideoStreamFramer.cpp#L1125

参考下live555 计算方法，264需要除以2，265不需要

**Comment by orestonce** [comment]
好，那需不需要也按照他的这段代码分析 `DeltaTfiDivisor` 的值？还是说直接写死h264除以2，h265除以1就行了
````cpp
    double prevDeltaTfiDivisor = DeltaTfiDivisor; 
    if (pic_struct_present_flag) {
      unsigned pic_struct = bv.getBits(4);
      DEBUG_PRINT(pic_struct);
      // Use this to set "DeltaTfiDivisor" (which is used to compute the frame rate):
      if (fHNumber == 264) {
	DeltaTfiDivisor =
	  pic_struct == 0 ? 2.0 :
	  pic_struct <= 2 ? 1.0 :
	  pic_struct <= 4 ? 2.0 :
	  pic_struct <= 6 ? 3.0 :
	  pic_struct == 7 ? 4.0 :
	  pic_struct == 8 ? 6.0 :
	  2.0;
      } else { // H.265
	DeltaTfiDivisor =
	  pic_struct == 0 ? 2.0 :
	  pic_struct <= 2 ? 1.0 :
	  pic_struct <= 4 ? 2.0 :
	  pic_struct <= 6 ? 3.0 :
	  pic_struct == 7 ? 2.0 :
	  pic_struct == 8 ? 3.0 :
	  pic_struct <= 12 ? 1.0 :
	  2.0;
      }
    } else {
      if (fHNumber == 264) {
	// Need to get field_pic_flag from slice_header to set this properly! #####
      } else { // H.265
	DeltaTfiDivisor = 1.0;
      }
    }
    // If "DeltaTfiDivisor" has changed, and we've already computed the frame rate, then
    // adjust it, based on the new value of "DeltaTfiDivisor":
    if (DeltaTfiDivisor != prevDeltaTfiDivisor && fParsedFrameRate != 0.0) {
      usingSource()->fFrameRate = fParsedFrameRate
	= fParsedFrameRate*(prevDeltaTfiDivisor/DeltaTfiDivisor);
````

**Comment by yapingcat** [comment]
https://github.com/rgaufman/live555/blob/2c92a57ca04b83b2038ab2ab701d05a54be06a85/liveMedia/H264or5VideoStreamFramer.cpp#L1125

```
unsigned num_units_in_tick, time_scale;
analyze_seq_parameter_set_data(num_units_in_tick, time_scale);
if (time_scale > 0 && num_units_in_tick > 0) {
	usingSource()->fFrameRate = fParsedFrameRate
	  = time_scale/(DeltaTfiDivisor*num_units_in_tick);
```

https://github.com/rgaufman/live555/blob/2c92a57ca04b83b2038ab2ab701d05a54be06a85/liveMedia/H264or5VideoStreamFramer.cpp#L201

`DeltaTfiDivisor(hNumber == 264 ? 2.0 : 1.0) `

可以直接写死

**Comment by orestonce** [comment]
好

**Comment by orestonce** [comment]
好，两个问题都解决了，谢谢大佬。
