### ISSUE TITLE
aac Decode时 out of range 【线上问题， 急】 

### ISSUE THREAD

**Issue by sunsky** [yapingcat/gomedia#156]
我 fork了https://github.com/sunsky/gomedia， 加了如下判断：
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/b7d2a49b-24a3-44ad-8afd-cd36fac75905">
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/950f3986-a27d-4ebc-95ca-7f3498444088">

但是 下游srs解析音频时会报错，且中断推流。
Error decoding AAC frame header.(Resource temporarily unavailable)
service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: consume audio
 : bridge consume audio : recode error : decode and resample : submit to dec(-1094995529,Invalid data found when processing input)

**Comment by yapingcat** [comment]
什么场景？

**Comment by sunsky** [comment]
> 什么场景？

 用gomedia推流RTSP （ h264 + aac ）给 srs 服务，但是 gomedia 会 crash同我上面报错：out fo range，我尝试加了判断后就不 crash， 但下游srs 遇到 aac 报错：Invalid data found when processing input， 说明aac音频是有问题的。

**Comment by yapingcat** [comment]
可以提供h264 和aac 来复现吗？

**Comment by yapingcat** [comment]
> > 什么场景？
> 
> 用gomedia推流RTSP （ h264 + aac ）给 srs 服务，但是 gomedia 会 crash同我上面报错：out fo range，我尝试加了判断后就不 crash， 但下游srs 遇到 aac 报错：Invalid data found when processing input， 说明aac音频是有问题的。

rtsp 走的udp？

**Comment by sunsky** [comment]
用的 TCP， 

https://github.com/user-attachments/assets/4580c61f-a9ed-44dd-88a3-fc60cd04f855

**Comment by sunsky** [comment]
无论 h264, h265 只要音频是Audio: aac (LC), 16000 Hz, mono, fltp ,就有问题

**Comment by yapingcat** [comment]
我这边没有复现这个问题，ffplay 播放看起来一切正常

**Comment by yapingcat** [comment]
> 用的 TCP，
> 
>  196.mp4

问下 srs 哪个版本支持rtsp  tcp推流的？印象中srs 只支持rtsp udp推流？

**Comment by sunsky** [comment]
> 中

最新版本。srs

**Comment by sunsky** [comment]
sry,  是aac音频传输环节有问题，产生了坏包，导致 srs crash。 感谢大佬的支持。
