### ISSUE TITLE
example request: remux ts and fix ts audio time pts

### ISSUE THREAD

**Issue by fastfading** [yapingcat/gomedia#16]
audio pts may not be consistant .
there may be overlap and gap between 2 aac package.
this will cause av not sync issue in some player ,   video.js chrome  for example.
could you add an example  to  fix ts audio time pts

Reference
https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxaudioframesdrift
https://github.com/video-dev/hls.js/blob/master/src/remux/mp4-remuxer.ts#L761

**Comment by yapingcat** [comment]
[Similar to this](https://github.com/yapingcat/gomedia/issues/14#issuecomment-1163280809)

you can refer to this code
