### ISSUE TITLE
bug: if pps sps is not the first Frame , its pts shows wrong

### ISSUE THREAD

**Issue by fastfading** [yapingcat/gomedia#17]
in  https://github.com/yapingcat/gomedia/blob/main/example/example_demux_ts.go#L45 
dump  pts and dts 

if the pps and sps is not the first frame ,   its pts and dts present the last frame pts

below is the first frame 
pts     dts     size  type
2899 2899 17 7           sps
2899 2899 8 8            pps
2899 2899 1274 5       IDR
2899 2899 11899 5
2932 2932 7036 1

below is not the first frame 
pts     dts     size  type
22602 22602 24163 1
22635 22635 17621 1
22635 22635 17 7   sps
22635 22635 8 8    pps
62455 62455 1238 5
62455 62455 61365 5
62455 62455 3611 5
62489 62489 61424 1
in this case there is a gap in pts,  
the same issue exist when there is no gap

**Comment by yapingcat** [comment]
could this cause any problems? play video failed ?

**Comment by fastfading** [comment]
it make remux  the  video frame  difficult.

**Comment by yapingcat** [comment]
please  test with the latest gomedia  version. the bug has been fixed

**Comment by fastfading** [comment]
修改后，现在[example_demux_ts.go#L45](https://github.com/yapingcat/gomedia/blob/main/example/example_demux_ts.go#L45)变成了

从
pts dts size type
2899 2899 17 7 sps
2899 2899 8 8 pps
2899 2899 1274 5 IDR
2899 2899 11899 5
2932 2932 7036 1
变成了
pts dts size type
2899 2899 17 7 sps
2899 2899 11899 5
2932 2932 7036 1

naltype 7， 8 和 5 被合并了，   这样在分析数据的时候反而不方便

**Comment by yapingcat** [comment]
可以使用 `codec.SplitFrame` 分割nalu

**Comment by yapingcat** [comment]
看你的日志输出, nalu type 7和5 没合并 ？

pts dts size type
2899 2899 17 7 sps
2899 2899 11899 5
2932 2932 7036 1

**Comment by fastfading** [comment]
> 看你的日志输出, nalu type 7和5 没合并 ？
> 
> pts dts size type 2899 2899 17 7 sps 2899 2899 11899 5 2932 2932 7036 1
sorry
写错了，
