### ISSUE TITLE
从外部引入包， 编译失败

### ISSUE THREAD

**Issue by fastfading** [yapingcat/gomedia#20]
好奇怪一个问题，   从外面引入这个包， 包中代码和git main 分支不一致，导致编译不过
❯ go mod init aabbcc
go: creating new go.mod: module aabbcc
❯ cp -r ~/git/golang/gomedia/example/example_play_mp4_with_hls.go ./
❯ go mod tidy
go: finding module for package github.com/yapingcat/gomedia/mpeg2
go: finding module for package github.com/yapingcat/gomedia/mp4
go: found github.com/yapingcat/gomedia/mp4 in github.com/yapingcat/gomedia/mp4 v0.0.0-20220617074658-94762898dc25
go: found github.com/yapingcat/gomedia/mpeg2 in github.com/yapingcat/gomedia/mpeg2 v0.0.0-20220617074658-94762898dc25
❯ go build
# aabbcc
./example_play_mp4_with_hls.go:65:51: undefined: mp4.SyncSample
./example_play_mp4_with_hls.go:121:17: info.EndDts undefined (type mp4.TrackInfo has no field or method EndDts)
./example_play_mp4_with_hls.go:124:24: demuxer.GetSyncTable undefined (type *mp4.MovDemuxer has no field or method GetSyncTable)
./example_play_mp4_with_hls.go:158:10: demuxer.SeekTime undefined (type *mp4.MovDemuxer has no field or method SeekTime)

**Comment by yapingcat** [comment]
需要先执行以下命令
go get github.com/yapingcat/gomedia

**Comment by fastfading** [comment]
新建一个工程， 理论上执行下面两步， 就能把对应的依赖都装好。 不需要 go get
go mod init aabbcc
go mod tidy

**Comment by yapingcat** [comment]
因为最开始的时候，gomedia在每个文件夹下面都有go.mod文件
所以你使用 go mod tidy 命令，下载下来是一个比较老的版本(即没有删除子文件夹go.mod文件的最后版本)

可能有方法解决，但是我现在还不知道.....。你有什么方法不？我也想解决这个问题

**Comment by fastfading** [comment]
手动指定  module， 能work ， 但是go mod tidy 始终报错

module aabbcc

go 1.18

require (
	github.com/yapingcat/gomedia v0.0.0-20220725070500-fec1566a2852
	// github.com/yapingcat/gomedia/mp4 v0.0.0-20220617074658-94762898dc25
	// github.com/yapingcat/gomedia/mpeg2 v0.0.0-20220617074658-94762898dc25
)

// require github.com/yapingcat/gomedia/codec v0.0.0-20220609081842-9e0c0e8a19a0 // indirect

**Comment by fastfading** [comment]
要不试试 ，直接删除 文件历史
https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history

**Comment by yapingcat** [comment]
把go.sum里面mp4,mpeg2,codec 都删除
或者你删除go.mod重新来,在go mod tidy之前先go get github.com/yapingcat/gomedia

**Comment by fastfading** [comment]
> 把go.sum里面mp4,mpeg2,codec 都删除 或者你删除go.mod重新来,在go mod tidy之前先go get github.com/yapingcat/gomedia

workaround 好办。 
但都不是标准做法。
最好办法是像上面一样， 彻底删除sub fold    go.mod 文件

**Comment by yapingcat** [comment]
> 要不试试 ，直接删除 文件历史
https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history
https://docs.github.com/cn/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

这个方法不行

**Comment by yapingcat** [comment]
先这么用着吧。暂时我也找不到好的办法.

**Comment by fastfading** [comment]
只能另启一个repo，或者删库重建。
 不然库引用多了，  每次tidy 都改一遍，蛮麻烦的，  而且库也要不断更新。
长痛不如短痛，

**Comment by yapingcat** [comment]
不需要每次tidy 都改一遍
只要在你第一次  tidy 之前 `go get github.com/yapingcat/gomedia` 就可以了

**Comment by fastfading** [comment]
不行的，  一样报错
rm -rf ~/go/pkg/mod/cache/download/github.com/yapingca
sudo rm -rf ~/go/pkg/mod/github.com/yapingcat
go get github.com/yapingcat/gomedia
go: downloading github.com/yapingcat/gomedia v0.0.0-20220726102614-25b1cb069adb
go: upgraded github.com/yapingcat/gomedia v0.0.0-20220725070500-fec1566a2852 => v0.0.0-20220726102614-25b1cb069adb
rm go.mod go.sum
go mod init aabbcc
❯ go mod tidy
go: finding module for package github.com/yapingcat/gomedia/mpeg2
go: finding module for package github.com/yapingcat/gomedia/mp4
go: found github.com/yapingcat/gomedia/mp4 in github.com/yapingcat/gomedia/mp4 v0.0.0-20220617074658-94762898dc25
go: found github.com/yapingcat/gomedia/mpeg2 in github.com/yapingcat/gomedia/mpeg2 v0.0.0-20220617074658-94762898dc25
❯ go build
# aabbcc
./example_play_mp4_with_hls.go:65:51: undefined: mp4.SyncSample
./example_play_mp4_with_hls.go:121:17: info.EndDts undefined (type mp4.TrackInfo has no field or method EndDts)
./example_play_mp4_with_hls.go:124:24: demuxer.GetSyncTable undefined (type *mp4.MovDemuxer has no field or method GetSyncTable)
./example_play_mp4_with_hls.go:158:10: demuxer.SeekTime undefined (type *mp4.MovDemuxer has no field or method SeekTime

**Comment by yapingcat** [comment]
在 `go mod init aabbcc` 和 `go mod tidy` 之间调用 `go get github.com/yapingcat/gomedia`

**Comment by yapingcat** [comment]
否则这个package 依赖关系 关联不上

**Comment by orestonce** [comment]
* 找到了一个比较好的解决方法: git push -f ， 强行覆盖以前的代码, 具体操作步骤
1. 保存当前代码到临时目录
2. 在主分支 git reset --hard "最初的第一个commit id"
3. 将最新代码拷贝到本地代码仓库,  然后执行 `git add . && git commit -m save && git push -f`
* 这样操作之后，远程的git仓库里就没有任何旧的commit记录了，在全新的环境下不用GOPROXY可以得到最新的go.mod， 但是以前使用过的人还是有问题, 需要再处理:
1. 本地删除 `~/go/` 目录，让本地缓存失效
2. 如果使用过 GOPROXY代理，需要通知 GOPROXY服务器的所有者，将 GOPROXY对应的服务器上的记录删除，或者切换到另一个没有缓存过这个仓库的 GOPROXY服务器

**Comment by yapingcat** [comment]
> * 找到了一个比较好的解决方法: git push -f ， 强行覆盖以前的代码, 具体操作步骤
>   
>   1. 保存当前代码到临时目录
>   2. 在主分支 git reset --hard "最初的第一个commit id"
>   3. 将最新代码拷贝到本地代码仓库,  然后执行 `git add . && git commit -m save && git push -f`
> * 这样操作之后，远程的git仓库里就没有任何旧的commit记录了，在全新的环境下不用GOPROXY可以得到最新的go.mod， 但是以前使用过的人还是有问题, 需要再处理:
>   
>   1. 本地删除 `~/go/` 目录，让本地缓存失效
>   2. 如果使用过 GOPROXY代理，需要通知 GOPROXY服务器的所有者，将 GOPROXY对应的服务器上的记录删除，或者切换到另一个没有缓存过这个仓库的 GOPROXY服务器

😭好麻烦哦.  还是让使用者自己用go get 吧😂

**Comment by orestonce** [comment]
> > * 找到了一个比较好的解决方法: git push -f ， 强行覆盖以前的代码, 具体操作步骤
> >   
> >   1. 保存当前代码到临时目录
> >   2. 在主分支 git reset --hard "最初的第一个commit id"
> >   3. 将最新代码拷贝到本地代码仓库,  然后执行 `git add . && git commit -m save && git push -f`
> > * 这样操作之后，远程的git仓库里就没有任何旧的commit记录了，在全新的环境下不用GOPROXY可以得到最新的go.mod， 但是以前使用过的人还是有问题, 需要再处理:
> >   
> >   1. 本地删除 `~/go/` 目录，让本地缓存失效
> >   2. 如果使用过 GOPROXY代理，需要通知 GOPROXY服务器的所有者，将 GOPROXY对应的服务器上的记录删除，或者切换到另一个没有缓存过这个仓库的 GOPROXY服务器
> 
> 😭好麻烦哦. 还是让使用者自己用go get 吧😂

长痛不如短痛，后续这个库如果火了肯定有很多人遇到这个坑

**Comment by orestonce** [comment]
或者把以前存在的package的路径废弃了，用新的路径试试
````
github.com/yapingcat/gomedia/dmp4
github.com/yapingcat/gomedia/dmpeg2
````

**Comment by yapingcat** [comment]
package的路径已经修改. 现在直接 `go mod tidy ` 可以下载最新的gomedia 版本

**Comment by orestonce** [comment]
额... 其实我想说在 package import path上使用 - 也不是什么好注意, 最好只使用 数字+小写英文字母

**Comment by orestonce** [comment]
可以达到的最完美的效果是在 ide里面输入最后一个目录名字,直接提示所有函数, 不需要 aliase就不存在package的最后一段可以表示两种package的易错问题, 最典型的就是 `math/rand`, `crypto/rand` , 在输入rand想自动提示的时候容易选错.
以-作为包的路径的一部分也有这个类似的问题

**Comment by yapingcat** [comment]
> 可以达到的最完美的效果是在 ide里面输入最后一个目录名字,直接提示所有函数, 不需要 aliase就不存在package的最后一段可以表示两种package的易错问题, 最典型的就是 `math/rand`, `crypto/rand` , 在输入rand想自动提示的时候容易选错.
> 以-作为包的路径的一部分也有这个类似的问题

不好意思，不是很理解。 为什么 _**以-作为包的路径的一部分也有这个类似的问题**_

在使用上我自测几个example，感觉这么改名使用上还可以。原来的代码除了修改 import路径，其他也不需要修改
不过我的使用体验基于vscode. ide 没试过

**Comment by orestonce** [comment]
import路径的最后一节和包名字不一样，导致阅读调用代码的时候需要花少量的时间成本去区分`mp4.BasicBox{}` 中的 `mp4.` 这是哪一个import引入进来的，如果有另一个import路径的最后一节和包名相同的mp4包，那在阅读代码、编写程序的时候就更混乱了

**Comment by orestonce** [comment]
````
package main

import "make/go-mp42" // 实际package名字是 mp4

func main() {
	mp4.Hello() //  需要花费少量成本辨别 “这里的mp4是哪里来的" 这件事，实际上可以避免
}
````

**Comment by yapingcat** [comment]
嗯,了解了.

目前，先这样吧，这种问题还在可以忍受范围内
