### ISSUE TITLE
flv转mp4报错？

### ISSUE THREAD

**Issue by Esword618** [yapingcat/gomedia#22]
用的你的例程。
`
package main

import (
	"fmt"
	"os"

	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-flv"
	"github.com/yapingcat/gomedia/go-mp4"
)

func FlvToMp4(Mp4FilePath, FlvFilePath string) {
	mp4file, err := os.OpenFile(Mp4FilePath, os.O_CREATE|os.O_RDWR, 0666)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer mp4file.Close()

	muxer, err := mp4.CreateMp4Muxer(mp4file)
	if err != nil {
		fmt.Println(err)
		return
	}
	vtid := muxer.AddVideoTrack(mp4.MP4_CODEC_H264)
	atid := muxer.AddAudioTrack(mp4.MP4_CODEC_AAC)

	flvfilereader, _ := os.Open(FlvFilePath)
	defer flvfilereader.Close()
	fr := flv.CreateFlvReader()

	fr.OnFrame = func(cid codec.CodecID, b []byte, pts, dts uint32) {
		if cid == codec.CODECID_AUDIO_AAC {
			err := muxer.Write(atid, b, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}

		} else if cid == codec.CODECID_VIDEO_H264 {
			err := muxer.Write(vtid, b, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}
		}
	}

	cache := make([]byte, 4096)
	for {
		n, err := flvfilereader.Read(cache)
		if err != nil {
			fmt.Println(err)
			break
		}
		fr.Input(cache[0:n])
	}
	err = muxer.WriteTrailer()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("flv转mp4完成！")
}

func main() {
	FlvToMp4("out.mp4", "out.flv")
}

`

错误：
`
EOF
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/yapingcat/gomedia/go-mp4.(*mp4track).makeStblTable(0xc00008c8f0)
        D:/goproject/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220731053213-04782526c441/go-mp4/mp4track.go:226 +0x552
github.com/yapingcat/gomedia/go-mp4.makeTrak(0xc00008c8f0, 0x1c060?)
        D:/goproject/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220731053213-04782526c441/go-mp4/trak-box.go:9 +0x19a
github.com/yapingcat/gomedia/go-mp4.(*Movmuxer).writeMoov(0xc0000d6000, {0xe87bc8, 0xc0000ce018})
        D:/goproject/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220731053213-04782526c441/go-mp4/mp4muxer.go:294 +0x1cb
github.com/yapingcat/gomedia/go-mp4.(*Movmuxer).WriteTrailer(0xc0000d6000)
        D:/goproject/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20220731053213-04782526c441/go-mp4/mp4muxer.go:219 +0x17c
main.FlvToMp4({0xe6005d?, 0x0?}, {0xe60056, 0x7})
        D:/goproject/src/MoocDownload/test/3.go:64 +0x37a
main.main()
        D:/goproject/src/MoocDownload/test/3.go:72 +0x2f
`

搞不懂为什么会出这样的错！
这个是视频链接：
链接：https://pan.baidu.com/s/1K4cl2kI6HSbKoSb_Fy32vg 
提取码：lttl 
--来自百度网盘超级会员V3的分享

**Comment by yapingcat** [comment]
我这边测试一切 正常

**Comment by yapingcat** [comment]
这个是必现的 ？

**Comment by yapingcat** [comment]
这个错误是因为没有对应的音视频帧写入到对应的track中

**Comment by Esword618** [comment]
在win上，你用的也是例程代码吗，如果不是，可否让我看一下，感谢。

**Comment by yapingcat** [comment]
确认一下，flv文件是否能正常打开，并读取数据

**Comment by Esword618** [comment]
可以，我这里使用的爱奇艺打开的。

**Comment by yapingcat** [comment]
我是用你这边提供的代码测试的，没报错

**Comment by Esword618** [comment]
好的，我在测试测试，看看原因，十分感谢

**Comment by yapingcat** [comment]
好的，可以加点打印日志，看看音视频数据有没有写入

**Comment by Esword618** [comment]
ok
