### ISSUE TITLE
Is it possible to take screenshots?

### ISSUE THREAD

**Issue by hasnhasan** [yapingcat/gomedia#24]
Is it possible to save as photo just like mp4 save?

**Comment by yapingcat** [comment]
sorry, gomedia can not do that.  you should take snapshot with ffmpeg

**Comment by hasnhasan** [comment]
I was able to use it by integrating with this lib.
https://github.com/nareix/joy4/blob/05a4ffbb53695aaacf9a2e2624472686280ab6dc/cgo/ffmpeg/video.go
