### ISSUE TITLE
mov读取支持

### ISSUE THREAD

**Issue by Tryanks** [yapingcat/gomedia#25]
mov与mp4的box封装格式几乎相同，但试图使用`mp4.CreateMp4Demuxer`打开mov文件时会返回mp4 Parser error
```Golang
mov, _ := os.Open("test.mov")
defer mov.Close()
md := mp4.CreateMp4Demuxer(mov)
if infos, err := md.ReadHead(); err != nil && err != io.EOF {
	panic(err)
}
```
请问我遗漏了什么内容、或是当前的MovDemuxer暂不支持吗？
mov文件是使用`ffmpeg -i test.mp4 -c copy test.mov`将任意mp4文件转封装后得到的

**Comment by Tryanks** [comment]
https://user-images.githubusercontent.com/49746336/189846511-69ec42dd-7a75-4b00-ab9c-17d6fa4d6bca.mov

**Comment by yapingcat** [comment]
收到，晚上我看看

**Comment by Tryanks** [comment]
已解决，伟大的工作，感谢。
