### ISSUE TITLE
example request: mpegts大文件切割成mpegts小文件 

### ISSUE THREAD

**Issue by hotraygroup** [yapingcat/gomedia#27]

**Comment by yapingcat** [comment]
不是很清楚这个需求目的。
如果是单纯的切割，而且这个切割操作比较频繁。不如在存ts文件的时候，搞一个索引文件记录关键帧的offset，这样读索引文件就可以了。

**Comment by hotraygroup** [comment]
rtsp--(pull)-->ffmpeg--(conv)-->mpegts--(read data from pipe)-->gomedia--(split)-->save mpegts files，在某些平台上用ffmpeg切割很不准确，考虑用gomedia切割成小文件
