### ISSUE TITLE
Support mpga audio codec in mpeg2.TSDemuxer

### ISSUE THREAD

**Issue by kbats183** [yapingcat/gomedia#29]
It would be amazing to have this feature, because vlc could generate http stream with audio not in aac codec.

For example, this sting capture webcamera and microfon on a linux `vlc -q v4l2:///dev/video0:chroma=h264:width=1920:height=1080 :input-slave=alsa://hw:1,0 --sout '#transcode{venc=x264{keyint=2},acodec=mpga,vb=0}:standard{access=http,mux=ts,dst=:8080,name=stream,mime=video/ts}'` or on windows `vlc -q dshow:// :dshow-adev="{you audio device name}" --sout "#transcode{venc=x264{keyint=1},vcodec=h264,acodec=mpga,vb=0}:http{access=http,mux=ts,dst=:8080/,name=stream,mime=video/ts}"`.

**Comment by yapingcat** [comment]
fix https://github.com/yapingcat/gomedia/commit/b29f96e10a45641fd891fa8bb2396d70b620fe11

please update to this version and try to test it again

**Comment by kbats183** [comment]
Great. Thank you!
