### ISSUE TITLE
ts packet must start with 0x47

### ISSUE THREAD

**Issue by orestonce** [yapingcat/gomedia#30]
[00001.ts.zip](https://github.com/yapingcat/gomedia/files/9806787/00001.ts.zip)
使用的转换代码: https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go

**Comment by yapingcat** [comment]
![image](https://user-images.githubusercontent.com/32125710/196347998-a31624f5-0569-4101-a07b-b16f5c0b1ebc.png)

第一个ts包 只有185个字节，不是标准的ts包

用vlc播放，有对应的日志输出
![image](https://user-images.githubusercontent.com/32125710/196348191-6b3c2f61-71de-4b38-be5e-d646796c647e.png)

**Comment by orestonce** [comment]
https://stackoverflow.com/a/34260830/4264448
> 
> At first, the parser should identify a proper packet boundary for the decoder to start decoding. The parser does this by:
 Identifying 3 sync words (0x47) in a row.
>   The distance between 2 sync words is 188 bytes.
>   If above 2 conditions are achieved,the parser assumes a proper packet boundary then on.

这么说的话，是不是应该跳过前面的不合法的ts数据

**Comment by yapingcat** [comment]
感谢，晚上我想想

**Comment by jiangslee** [comment]
> 感谢，晚上我想想

大佬，想好怎么干掉这个bug了不？

**Comment by yapingcat** [comment]
周末我改一下

**Comment by yapingcat** [comment]
可以更新到最新版本测试看看
有条件的话可以多测试，我只是简单自测了几个测试用例，代码看着没问题，但是我不确定这次修改是否会引入一些bug....

**Comment by orestonce** [comment]
@jiangslee 更新了gomedia依赖, 试试新版: https://github.com/orestonce/m3u8d/releases/tag/v1.15.20

**Comment by jiangslee** [comment]
@orestonce 我试了能正常合并了。
