### ISSUE TITLE
ps流文件转mp4报错，无法转换

### ISSUE THREAD

**Issue by xiaokuang95** [yapingcat/gomedia#34]
func main() {
	tsfile := "1666971231078.ps"
	tsFd, err := os.Open(tsfile)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer tsFd.Close()

	hasAudio := false
	hasVideo := false
	var atid uint32 = 0
	var vtid uint32 = 0

	mp4filename := "convert_ps.mp4"
	mp4file, err := os.OpenFile(mp4filename, os.O_CREATE|os.O_RDWR, 0666)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer mp4file.Close()

	muxer, err := mp4.CreateMp4Muxer(mp4file)
	if err != nil {
		fmt.Println(err)
		return
	}

	demuxer := mpeg2.NewPSDemuxer()
	//demuxer := mpeg2.NewTSDemuxer()
	demuxer.OnFrame = func(frame []byte, cid mpeg2.PS_STREAM_TYPE, pts uint64, dts uint64) {
		if cid == mpeg2.PS_STREAM_H264 {
			if !hasVideo {
				vtid = muxer.AddVideoTrack(mp4.MP4_CODEC_H264)
				hasVideo = true
			}
			err := muxer.Write(vtid, frame, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}
		} else if cid == mpeg2.PS_STREAM_AAC {
			if !hasAudio {
				atid = muxer.AddAudioTrack(mp4.MP4_CODEC_AAC)
				hasAudio = true
			}
			err := muxer.Write(atid, frame, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}
		} else if cid == mpeg2.PS_STREAM_G711A {
			if !hasAudio {
				atid = muxer.AddAudioTrack(mp4.MP4_CODEC_G711A)
				hasAudio = true
			}
			err := muxer.Write(atid, frame, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}
		} else if cid == mpeg2.PS_STREAM_G711U {
			if !hasAudio {
				atid = muxer.AddAudioTrack(mp4.MP4_CODEC_G711U)
				hasAudio = true
			}
			err := muxer.Write(atid, frame, uint64(pts), uint64(dts))
			if err != nil {
				fmt.Println(err)
			}
		}
	}
	demuxer.OnPacket = func(pkg mpeg2.Display, decodeResult error) {

	}
	buf, _ := ioutil.ReadAll(tsFd)
	fmt.Printf("read %d size\n", len(buf))
	fmt.Println(demuxer.Input(buf))
	err = muxer.WriteTrailer()
	if err != nil {
		fmt.Errorf("err:%v", err)
		return
	}
}
执行到muxer.WriteTrailer() 报错 panic: runtime error: index out of range [308] with length 308

**Comment by xiaokuang95** [comment]
系统 win11
错误详细详细：
panic: runtime error: index out of range [308] with length 308

goroutine 1 [running]:
github.com/yapingcat/gomedia/go-mp4.(*mp4track).makeStblTable(0xc000094410)
        C:/Users/Administrator/GolandProjects/gomedia/go-mp4/mp4track.go:210 +0xaf1
github.com/yapingcat/gomedia/go-mp4.makeTrak(0xc000094410, 0xbc480?)
        C:/Users/Administrator/GolandProjects/gomedia/go-mp4/trak-box.go:9 +0x19a
github.com/yapingcat/gomedia/go-mp4.(*Movmuxer).writeMoov(0xc0000d4000, {0x1040438, 0xc0000ca020})
        C:/Users/Administrator/GolandProjects/gomedia/go-mp4/mp4muxer.go:297 +0x209
github.com/yapingcat/gomedia/go-mp4.(*Movmuxer).WriteTrailer(0xc0000d4000)
        C:/Users/Administrator/GolandProjects/gomedia/go-mp4/mp4muxer.go:219 +0x17c
main.main()
        C:/Users/Administrator/GolandProjects/gomedia/example/example_convert_ps_mp4.go:86 +0x4a6

**Comment by yapingcat** [comment]
可以上传一下测试的ps文件吗

**Comment by xiaokuang95** [comment]
> 可以上传测试的ps文件不？

https://github.com/xiaokuang95/public/blob/main/1666972997252.ps

**Comment by yapingcat** [comment]
更新到最新版本在测试一下

测试代码也要改一下，在增加音频track的时候需要指定通道和采样率,否则播放会有问题
`muxer.AddAudioTrack(mp4.MP4_CODEC_G711A, mp4.WithAudioChannelCount(2), mp4.WithAudioSampleRate(8000))`

**Comment by xiaokuang95** [comment]
> 更新到最新版本在测试一下
> 
> 测试代码也要改一下，在增加音频track的时候需要指定通道和采样率,否则播放会有问题，类似代码如下 `muxer.AddAudioTrack(mp4.MP4_CODEC_G711A, mp4.WithAudioChannelCount(2), mp4.WithAudioSampleRate(8000))`

感谢，可以了

**Comment by yapingcat** [comment]
G711a和G711u需要指定采样率和通道数，其他音频格式会自动设置这些参数，不需要设置
