### ISSUE TITLE
hls flv 支持流形式转换？

### ISSUE THREAD

**Issue by xiaokuang95** [yapingcat/gomedia#35]
例如 摄像头的ps流，转换为hls、flv格式的在网页上实时画面，目前发现的是example提供的是都是file的存在，如果是ps流这种是否支持流转换输出

**Comment by yapingcat** [comment]
支持。只要调用 ps dexmuer 的Input接口即可
`func (psdemuxer *PSDemuxer) Input(data []byte) error`
至于这个data 是来自文件还是网络没有要求，你只需要把ps包调用接口，塞入到ps demuxer中即可

**Comment by xiaokuang95** [comment]
> 支持。只要调用 ps dexmuer 的Input接口即可 `func (psdemuxer *PSDemuxer) Input(data []byte) error` 这个data 既可以是来自读取的文件也可以是从网络中接收，总之你只需要把ps包通过这个接口塞入到ps demuxer中即可

ps 是否可以直接转hls 或者 mp4 我看到的eaxmple 里面是mp4 必须是一个io.WriteSeeker 我目前想到个笨办法就是ps先转mp4在封装为flv或者m3u8，但是看到mp4的创建必须是一个write流

**Comment by yapingcat** [comment]
可以参考下面代码，ps转flv，
FlvWriter 传入的是 io.Writer，配合golang标准库，可以是os.File，也可以是http.ResponseWriter等等其他
你也可以根据你的业务需求自己去实现 io.Writer 接口
````golang
package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-flv"
	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {
	psfile := os.Args[1]
	rfd, _ := os.Open(psfile)
	defer rfd.Close()
	buf, _ := ioutil.ReadAll(rfd)
	fmt.Printf("read %d size\n", len(buf))

	flvfilename := "convert_ps.flv"
	flvfile, err := os.OpenFile(flvfilename, os.O_CREATE|os.O_RDWR, 0666)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer flvfile.Close()
	writer := flv.CreateFlvWriter(flvfile)
	writer.WriteFlvHeader()
	demuxer := mpeg2.NewPSDemuxer()
	demuxer.OnFrame = func(frame []byte, cid mpeg2.PS_STREAM_TYPE, pts uint64, dts uint64) {
		if cid == mpeg2.PS_STREAM_H264 {
			if codec.H264NaluType(frame) == 9 {
				return
			}
			writer.WriteH264(frame, uint32(pts), uint32(dts))
		} else if cid == mpeg2.PS_STREAM_G711A {
			writer.WriteG711A(frame, uint32(pts), uint32(dts))
		}
	}
	fmt.Println(demuxer.Input(buf))
	demuxer.Flush()
}

````

**Comment by yapingcat** [comment]
至于转hls，可以参考这个[example_play_mp4_with_hls](https://github.com/yapingcat/gomedia/blob/main/example/example_play_mp4_with_hls.go)

用法大致类似

**Comment by xiaokuang95** [comment]
> 至于转hls，可以参考这个[example_play_mp4_with_hls](https://github.com/yapingcat/gomedia/blob/main/example/example_play_mp4_with_hls.go)
> 
> 用法大致类似

好的，我去试试看，谢谢

**Comment by xiaokuang95** [comment]
> 至于转hls，可以参考这个[example_play_mp4_with_hls](https://github.com/yapingcat/gomedia/blob/main/example/example_play_mp4_with_hls.go)
> 
> 这个例子是mp4转hls，其实用法大致类似，对于gomedia 这些库，输入输出音视频格式都是一致的，视频都是annex-b形式的h264/h265,aac 都是带adts头的帧 等等

我之前理解错了，我理解为一种格式 例如 ps只能转mp4然后mp4才能转hls或者flv

**Comment by xiaokuang95** [comment]
> 可以参考下面代码，ps转flv， FlvWriter 传入的是 io.Writer，配合golang标准库，可以是os.File，也可以是http.ResponseWriter等等其他 你也可以根据你的业务需求自己去实现 io.Writer 接口
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"io/ioutil"
> 	"os"
> 
> 	"github.com/yapingcat/gomedia/go-codec"
> 	"github.com/yapingcat/gomedia/go-flv"
> 	"github.com/yapingcat/gomedia/go-mpeg2"
> )
> 
> func main() {
> 	psfile := os.Args[1]
> 	rfd, _ := os.Open(psfile)
> 	defer rfd.Close()
> 	buf, _ := ioutil.ReadAll(rfd)
> 	fmt.Printf("read %d size\n", len(buf))
> 
> 	flvfilename := "convert_ps.flv"
> 	flvfile, err := os.OpenFile(flvfilename, os.O_CREATE|os.O_RDWR, 0666)
> 	if err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 	defer flvfile.Close()
> 	writer := flv.CreateFlvWriter(flvfile)
> 	writer.WriteFlvHeader()
> 	demuxer := mpeg2.NewPSDemuxer()
> 	demuxer.OnFrame = func(frame []byte, cid mpeg2.PS_STREAM_TYPE, pts uint64, dts uint64) {
> 		if cid == mpeg2.PS_STREAM_H264 {
> 			if codec.H264NaluType(frame) == 9 {
> 				return
> 			}
> 			writer.WriteH264(frame, uint32(pts), uint32(dts))
> 		} else if cid == mpeg2.PS_STREAM_G711A {
> 			writer.WriteG711A(frame, uint32(pts), uint32(dts))
> 		}
> 	}
> 	fmt.Println(demuxer.Input(buf))
> 	demuxer.Flush()
> }
> ```

不行，直接花屏了

**Comment by yapingcat** [comment]
可以把ps流导出来发给我一份吗？

**Comment by xiaokuang95** [comment]
> 不行，直接花屏了 我获取到ps流，然后转为flv文件存储，用ffplay 直接花屏

https://github.com/xiaokuang95/public/blob/main/1667208635925.ps

**Comment by xiaokuang95** [comment]
> 可以把ps流导出来发给我一份吗？

https://github.com/xiaokuang95/public/blob/main/1667208635925.ps

**Comment by xiaokuang95** [comment]
> 可以把ps流导出来发给我一份吗？

如果是完整的ps流文件转换，没发送花屏，但是如果是流实时转换就会花，是不是我频繁demuxer.Flush() 接收到流我就会转换然后flush一次

**Comment by yapingcat** [comment]
`demuxer.Flush()  `  应该要在结束的时候调用，且只调用一次

**Comment by xiaokuang95** [comment]
> `demuxer.Flush() ` 应该要在ps流结束的时候调用，且只调用一次

这个是实时流，不是一个固定的文件，不刷新，转换是生效的？

**Comment by xiaokuang95** [comment]
我用文件的ps转换为flv的视频文件 音频好像提（升）调了

**Comment by yapingcat** [comment]
恩，`demuxer.Flush` 的作用是把可能存在的缓存做一次帧数据回调，避免丢失数据

**Comment by yapingcat** [comment]
> 我用文件的ps转换为flv的视频文件 音频好像提（升）调了

你的采样率是多少？

**Comment by xiaokuang95** [comment]
> > 我用文件的ps转换为flv的视频文件 音频好像提（升）调了
> 
> 你的采样率是多少？

8000

**Comment by xiaokuang95** [comment]
> > > 我用文件的ps转换为flv的视频文件 音频好像提（升）调了
> > 
> > 
> > 你的采样率是多少？
> 
> G711A 8000

**Comment by xiaokuang95** [comment]
> G711A 8000

G711A 8000

> > 我用文件的ps转换为flv的视频文件 音频好像提（升）调了
> 
> 你的采样率是多少？

G711A 8000

**Comment by yapingcat** [comment]
> > > 我用文件的ps转换为flv的视频文件 音频好像提（升）调了
> > 
> > 
> > 你的采样率是多少？
> 
> G711A 8000

通道数写错了，稍等我改一下

**Comment by yapingcat** [comment]
麻烦最新到版本，测试看看

**Comment by xiaokuang95** [comment]
> 麻烦更新至最新版本，测试看看

好的，我试试

**Comment by xiaokuang95** [comment]
> 麻烦更新至最新版本，测试看看

正常了

**Comment by xiaokuang95** [comment]
> 麻烦更新至最新版本，测试看看

提供一下收款码，辛苦了，请你喝杯![3FBX4FO%F224@% Q1_`I@VQ](https://user-images.githubusercontent.com/33177184/198992375-7b299d2e-a7c6-4fd1-a6c1-701f0c41e093.png)

**Comment by yapingcat** [comment]
> > 麻烦更新至最新版本，测试看看
> 
> 提供一下收款码，辛苦了，请你喝杯![3FBX4FO%F224@% Q1_`I@VQ](https://user-images.githubusercontent.com/33177184/198992375-7b299d2e-a7c6-4fd1-a6c1-701f0c41e093.png)

不需要啦，我做这个完全是因为兴趣，我也很开心你能使用gomedia

**Comment by xiaokuang95** [comment]
> > > 麻烦更新至最新版本，测试看看
> > 
> > 
> > 提供一下收款码，辛苦了，请你喝杯![3FBX4FO%F224@% Q1_`I@VQ](https://user-images.githubusercontent.com/33177184/198992375-7b299d2e-a7c6-4fd1-a6c1-701f0c41e093.png)
> 
> 不需要啦，我做这个完全是因为兴趣，我也很开心你能使用gomedia

好吧，感谢这2天的帮助

**Comment by yapingcat** [comment]
对了，你的音视频时间戳不是从0 开始的，音频的时间戳也有点不太对，转成flv之后 vlc播放会有点问题，如果要解决这个问题可以参考下面的代码

````golang
package main

import (
	"fmt"
	"os"

	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-flv"
	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {
	psfile := os.Args[1]
	rfd, _ := os.Open(psfile)
	defer rfd.Close()

	flvfilename := "convert_ps.flv"
	flvfile, err := os.OpenFile(flvfilename, os.O_CREATE|os.O_RDWR, 0666)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer flvfile.Close()
	writer := flv.CreateFlvWriter(flvfile)
	writer.WriteFlvHeader()
	lastPts := uint64(0)
	videoPts := uint32(0)
	audioPts := uint32(0)
	first := true
	demuxer := mpeg2.NewPSDemuxer()
	demuxer.OnFrame = func(frame []byte, cid mpeg2.PS_STREAM_TYPE, pts uint64, dts uint64) {
		if cid == mpeg2.PS_STREAM_H264 {
			if codec.H264NaluType(frame) == 9 {
				return
			}
			if first {
				first = false
			} else {
				codec.SplitFrameWithStartCode(frame, func(nalu []byte) bool {
					nalu_type := codec.H264NaluType(nalu)
					if nalu_type <= codec.H264_NAL_I_SLICE {
						videoPts += uint32(pts - lastPts)
					}
					return true
				})
			}
			lastPts = pts
			writer.WriteH264(frame, uint32(videoPts), uint32(videoPts))
		} else if cid == mpeg2.PS_STREAM_G711A {
			fmt.Println(pts, dts)
			writer.WriteG711A(frame, uint32(audioPts), uint32(audioPts))
			audioPts += uint32(len(frame) / 8)
		}
	}

	for {
		buf := make([]byte, 4096)
		ret, err := rfd.Read(buf)
		if err != nil {
			fmt.Println(err)
			break
		}
		demuxer.Input(buf[:ret])
	}

	demuxer.Flush()
}

````
