### ISSUE TITLE
ps实时流转flv实时流，不能长时间播放

### ISSUE THREAD

**Issue by xiaokuang95** [yapingcat/gomedia#37]
ps实时流转flv实时流，长时间播放会自动断开，播放的客户端用的是ffplay

**Comment by yapingcat** [comment]
ffplay 有什么错误的日志输出吗？

**Comment by xiaokuang95** [comment]
> ffplay 日志 贴一下？

按照 example_http_flv_server.go 写的flv server 提升的是 写端超时了，客户端断开链接了 
![image](https://user-images.githubusercontent.com/33177184/199423186-6f038e3f-232b-4718-9ab2-cce2562ce0f0.png)

**Comment by yapingcat** [comment]
1.  need more bytes 这个错误没有处理吧？
2.  如果 提示了i/o timeout，用netstat 查看是否有缓存堆积？

**Comment by xiaokuang95** [comment]
> 1. need more bytes 这个错误没有处理吧？
> 2. 如果 提示了i/o timeout，用netstat 查看是否有缓存堆积？

目前是ffplay没有自动断开，提示的还是在拉取流，然后画面就卡住那断开的追后一针的，不清楚，是不是异常need more bytes ，导致没接收到数据，主动断开，还是什么其他原因，need more bytes 造成的原因是什么，我ps流是根据排序后转码的，理论上，应该不会有问题的

**Comment by yapingcat** [comment]
need more bytes 表示当前解析的不是一个完整的ps包，但是ps包结构上没有错误。这个错误可以忽略不用管

**Comment by xiaokuang95** [comment]
> need more bytes 表示当前解析的不是一个完整的ps包，但是ps包结构上没有错误。这个错误可以忽略不用管

那为什么客户端会自动断开连接，是flv的问题？

**Comment by xiaokuang95** [comment]
> need more bytes 表示当前解析的不是一个完整的ps包，但是ps包结构上没有错误。这个错误可以忽略不用管
目前测试是3分钟内必会断开连接

**Comment by yapingcat** [comment]
出现了io/timeout 错误，估计有可能时网络拥塞了吧，
这个错误不是flv库中产生的，是由http.ResponseWriter 返回的。

**Comment by yapingcat** [comment]
方便抓个包看一下吗？

**Comment by yapingcat** [comment]
看日志是localhost拉流网络应该是ok的
可以保存一份flv文件看看码流是否有问题，发不出去也有可能是ffplay不收了

**Comment by xiaokuang95** [comment]
> 
https://github.com/xiaokuang95/public/blob/main/flv.pcapng 客户端端口是45260 服务端是8080

**Comment by yapingcat** [comment]
![DIa3RlvaD1](https://user-images.githubusercontent.com/32125710/199436972-55a09f3f-ebb0-4df0-bdaf-1d4acc494d85.jpg)

抓包看发流正常，但是服务端主动发了fin包，关闭了连接
你的码率应该时2M码率吧，但是实际抓包看接近6M了，发流速度正常吗？

**Comment by xiaokuang95** [comment]
> ![DIa3RlvaD1](https://user-images.githubusercontent.com/32125710/199436972-55a09f3f-ebb0-4df0-bdaf-1d4acc494d85.jpg)
> 
> 抓包看发流正常，但是服务端主动发了fin包，关闭了连接 你的码率应该时2M码率吧，但是实际抓包看接近4-5M了，发流速度正常吗？
目前是接收到ps流就直接丢去转码了，没有进行分包处理，奇怪了，怎么会是服务器端自动断开的，我看http接口没有显示断开呀，除非我主动断开了，http才会断开

**Comment by xiaokuang95** [comment]
![image](https://user-images.githubusercontent.com/33177184/199443159-280b2716-b2a6-4624-a9be-f9a063f3744d.png)
这是flv-server
![image](https://user-images.githubusercontent.com/33177184/199443322-3155063d-db91-4ca2-a1a1-c3854a3fdfb1.png)
这是写入对端数据

**Comment by yapingcat** [comment]
创建http.server的时候是不是设置读写超时了，可以检查一下

**Comment by xiaokuang95** [comment]
> 创建http.server的时候是不是设置读写超时了，可以检查一下

我这边http设置的问题，我设置为60秒超时了，不好意思

**Comment by xiaokuang95** [comment]
请教个问题，PSDemuxer 如何并发读取数据，目前是并发读取数据就会花屏，不并发读取数据，会导致后门启动访问的必须要等待前面人发送完成，才会继续发送后面的

砂糖橘 ***@***.***> 于2022年11月2日周三 17:23写道：

**Comment by yapingcat** [comment]
gomedia的这些库不保证线程安全，由调用者来保证线程安全

**Comment by yapingcat** [comment]
而且对于同一个 psdemuxer 为什么会并发读取数据呢，应该是一个协程处理一个会话才对

**Comment by xiaokuang95** [comment]
不是这样的，是一个http请求就会创建一个 psdemuxer ，然后单独有一个go runtime 进行根据通道区分
，ps流数据是一份，psdemuxer 是多分，就会进行循环input


砂糖橘 ***@***.***> 于2022年11月2日周三 18:15写道：

**Comment by yapingcat** [comment]
同一个ps数据包是可以放入多个ps demuxer的，可以考虑一下ps 数据包的slice，有没有可能被其他协程覆写掉

**Comment by xiaokuang95** [comment]
[image: image.png]
我只要用到go runtime 要么是花屏，要么1分钟不到就会崩溃，ps流的[]byte，我已经做好了copy处理，应该是还是内部不支持多线程的操作

砂糖橘 ***@***.***> 于2022年11月2日周三 18:37写道：

**Comment by xiaokuang95** [comment]
[image: image.png]我在发送ps流的时候就做了ps流的copy，发送的也是copy的那份

razy c ***@***.***> 于2022年11月2日周三 19:09写道：
