### ISSUE TITLE
ts转mp4报OUT OF RANGE

### ISSUE THREAD

**Issue by xm0625** [yapingcat/gomedia#41]
该问题从`commit：18af6a81eb5b0874aff81fbcd6f01a8b6a47543c`开始引入

回退到`commit：6a8b0915fd0d0fd1ef8fb7a9b7aab2e83a3b63f7` 问题消失

**Comment by xm0625** [comment]
http://devimages.apple.com/iphone/samples/bipbop/gear4/prog_index.m3u8

**Comment by yapingcat** [comment]
麻烦，更新到最新版本测试看看

**Comment by xm0625** [comment]
fixed!
