### ISSUE TITLE
从go get下来的mpeg代码,写PAT时有问题

### ISSUE THREAD

**Issue by xiaozhihong** [yapingcat/gomedia#44]
![image](https://user-images.githubusercontent.com/8449258/213344209-73aa5ba4-3d9e-4426-9b5c-312240caef33.png)

这里不需要++, 看了下github上目前的代码, 没有问题, 希望能推一个新的版本上去. 感谢

**Comment by yapingcat** [comment]
估计是下了老版本了,
确认一下 import的package 是否是 `github.com/yapingcat/gomedia/go-mpeg2`

**Comment by xiaozhihong** [comment]
感谢, 我看了下用的是github.com/yapingcat/gomedia/mpeg2, 改成了github.com/yapingcat/gomedia/go-mpeg2了, 一切正常
