### ISSUE TITLE
关于网络流录成flv

### ISSUE THREAD

**Issue by czk630597526** [yapingcat/gomedia#46]
我现在rtsp拉出来一路视频，一路音频，如果我想把他们录成flv，这应该怎么操作呢？

**Comment by czk630597526** [comment]
或者说，有两个文件，一个h264文件，一个aac文件，怎么把他合成一个flv

**Comment by yapingcat** [comment]
rtsp 和 flv 用的都是gomedia吗？

**Comment by czk630597526** [comment]
> rtsp 和 flv 用的都是gomedia吗？

谢答复，rtsp不用gomedia，我现在有自己的平台，想着做个录制的功能，不知道好操作不

**Comment by yapingcat** [comment]
> > rtsp 和 flv 用的都是gomedia吗？
> 
> 谢答复，rtsp不用gomedia，我现在有自己的平台，想着做个录制的功能，不知道好操作不

可以的,类似下面这样
````golang
flvFile, _ := os.OpenFile("rtsp.flv", os.O_CREATE|os.O_RDWR, 0666)
defer flvFile.Close()
fw := flv.CreateFlvWriter(flvFile)
fw.WriteFlvHeader()

//写入音视频数据
fw.WriteH264(b, pts, dts) 

fw.WriteG711A(b,pts,dts)

````

flv的时间戳单位时毫秒，和rtsp不一样，视频一般需要 除以90，音频根据采样率来转换

**Comment by czk630597526** [comment]
> > > rtsp 和 flv 用的都是gomedia吗？
> > 
> > 
> > 谢答复，rtsp不用gomedia，我现在有自己的平台，想着做个录制的功能，不知道好操作不
> 
> 可以的,类似下面这样
> 
> ```go
> flvFile, _ := os.OpenFile("rtsp.flv", os.O_CREATE|os.O_RDWR, 0666)
> defer flvFile.Close()
> fw := flv.CreateFlvWriter(flvFile)
> fw.WriteFlvHeader()
> 
> //写入音视频数据
> fw.WriteH264(h264FrameData, pts, dts) 
> 
> fw.WriteG711A(g711aFrameData,pts,dts)
> ```
> 
> flv的时间戳单位是毫秒，和rtsp不一样，所以对于rtsp时间戳，视频一般需要 除以90，音频根据采样率来转换

谢谢作者，我去试试看
