### ISSUE TITLE
mp4 demuxer: decodeESDescriptor panics

### ISSUE THREAD

**Issue by iMro0t** [yapingcat/gomedia#47]
https://github.com/yapingcat/gomedia/blob/6d6ac05461eae39f78ca845cd12ae43192607bd5/go-mp4/esds-box.go#L111-L134

this code panics with slice out of bound error. attaching demo content.  

demo content url `https://user-images.githubusercontent.com/25949138/216256532-2f2ab347-9562-474f-8e7e-937b48346983.mp4`

```go
package main

import (
	"bytes"
	"github.com/yapingcat/gomedia/go-mp4"
	"io"
	"net/http"
)

func main() {
	demoMp4 := "https://user-images.githubusercontent.com/25949138/216256532-2f2ab347-9562-474f-8e7e-937b48346983.mp4"
	resp, err := http.Get(demoMp4)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	demuxer := mp4.CreateMp4Demuxer(bytes.NewReader(body))
	_, err = demuxer.ReadHead()
	if err != nil {
		panic(err)
	}
}

```

**Comment by shhahid7** [comment]
@iMro0t **brother,** i want to talk to you. how can i speak with you? kindly share your contact!! thanks
