### ISSUE TITLE
mp4muxer_test的	tid := muxer.AddAudioTrack(MP4_CODEC_AAC, 2, 16, 44100)

### ISSUE THREAD

**Issue by pandason125** [yapingcat/gomedia#51]
mp4muxer_test.go:146:44: cannot use 2 (untyped int constant) as TrackOption value in argument to muxer.AddAudioTrack
mp4muxer_test.go:146:47: cannot use 16 (untyped int constant) as TrackOption value in argument to muxer.AddAudioTrack
mp4muxer_test.go:146:51: cannot use 44100 (untyped int constant) as TrackOption value in argument to muxer.AddAudioTrack
提示这些参数传递有问题，谁能帮忙指点怎么改

**Comment by yapingcat** [comment]
不好意思，单元测试的代码 一直没有按照最新版本进行修改，
最新版本的用法

```
muxer.AddAudioTrack(mp4.MP4_CODEC_AAC,mp4.WithAudioSampleRate(44100))

```

对于aac，gomedia内部会自动识别采样率等参数，所以对于aac只需要`muxer.AddAudioTrack(mp4.MP4_CODEC_AAC)` 就可以了

**Comment by pandason125** [comment]
> 

可以

**Comment by pandason125** [comment]
ps-demuxer_test.go的72行                OnPacket:  tt.fields.OnPacket,
sdp_test.go的27行		err := sdp.ParserSdp([]byte(sdpstr))
也是报错，如果可以麻烦看看

**Comment by pandason125** [comment]
sdp_test.go的27行 err := sdp.ParserSdp([]byte(sdpstr))
改成	err := sdp.ParserSdp(sdpstr)

**Comment by yapingcat** [comment]
提个PR？
