### ISSUE TITLE
example_rtmp_play_client.go 拉流，导致rtmp server崩溃

### ISSUE THREAD

**Issue by xiaokuang95** [yapingcat/gomedia#56]
server 采用的是 example_rtmp_server.go
报错信息：
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).handlePlay(0xc000134100, {0xc0000125c7, 0x2c, 0x2c})
github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:392 +0xb11
![image](https://user-images.githubusercontent.com/33177184/224882946-b4159d4e-d7c4-4c6e-8991-f7abcc944f19.png)

**Comment by yapingcat** [comment]
感谢，已经修复
