### ISSUE TITLE
支持rtp转rtmp？

### ISSUE THREAD

**Issue by xiaokuang95** [yapingcat/gomedia#58]
目前采用example的代码，获取到rtph的264码流，然后推送到rtmp server，画面能出现，但是基本像假死了一样，半天画面没反应
推送代码用的是example/example_rtmp_publish_client.go

**Comment by xiaokuang95** [comment]
获取到的264的码流的前面进行了00 00 00 01的追加的

**Comment by yapingcat** [comment]
看描述是支持这种场景的，我怀疑是不是时间戳没设置正确，方便贴下代码吗

**Comment by xiaokuang95** [comment]
> 

时间戳我用的是rtp的那个timestamp

**Comment by yapingcat** [comment]
> 时间戳我用的是rtp的那个timestamp

rtmp的时间戳单位是毫秒，不能直接用rtp的时间戳，把视频rtp的时间戳除以90在测试看看，音频先丢弃

**Comment by xiaokuang95** [comment]
```
package main

import (
	prtp "github.com/pion/rtp"
	"github.com/yapingcat/gomedia/go-codec"
	"net"
	"publish.demo/pkg/rtmp"
	"publish.demo/pkg/rtp"
	"publish.demo/pkg/util"
)
func main() {
        host := "192.168.2.168"
	rtmpUrl := "rtmp://192.168.2.168:1935/live/test"
	var queue = rtp.NewRtpQueue()
	publishClient, _ := rtmp.NewRTMPClient(rtmpUrl, rtmp.PUBLISH)
	var udp = rtp.NewRtpUDPStream(host, rtp.DefaultPortMin, rtp.DefaultPortMax, func(pkt []byte, laddr, raddr net.Addr) {
		packet := &prtp.Packet{}
		packet.Unmarshal(pkt)
		queue.Write(packet)
		oldPkt := queue.Read(packet.Timestamp, packet.Marker)
		if oldPkt == nil {
			return
		}
		err := publishClient.GetRtmpClient().WriteVideo(codec.CODECID_VIDEO_H264, oldPkt.Payload, oldPkt.Timestamp, oldPkt.Timestamp)
		if err != nil {
			util.Errorf(err.Error())
		}
	})
	go udp.Read()
}
```

**Comment by xiaokuang95** [comment]
> > 时间戳我用的是rtp的那个timestamp
> 
> rtmp的时间戳单位是毫秒，不能直接用rtp的时间戳，把视频rtp的时间戳除以90在测试看看，音频先丢弃

/90还是不行 
![image](https://user-images.githubusercontent.com/33177184/225910951-6a2bb901-07bb-4864-a98c-c11ebe7381a9.png)
画面获取到了，但是后面的就不动了

**Comment by yapingcat** [comment]
我明白了，直接使用rtp的payload 是不行的，因为不是完整的一帧数据，请使用 go-rtsp 下面的rtp包用于提取h264数据 https://github.com/yapingcat/gomedia/blob/0cf3fb84012e5cc67a387fabe95ee90313d1952d/go-rtsp/rtp/rtp-h264.go#L218

**Comment by xiaokuang95** [comment]
> 我明白了，直接使用rtp的payload 是不行的，因为不是完整的一帧数据，请使用 go-rtsp 下面的rtp包用于提取h264数据
> 
> https://github.com/yapingcat/gomedia/blob/0cf3fb84012e5cc67a387fabe95ee90313d1952d/go-rtsp/rtp/rtp-h264.go#L218

那个我是做了封装的queue.read 读取的是完整的一帧

**Comment by xiaokuang95** [comment]
``` go
func (q *rtpQueue) Read(timestamp uint32, marker bool) *prtp.Packet {
	if marker {
		pkts := q.timestamps[timestamp]
		q.timestamps[timestamp] = nil
		if pkts == nil {
			return nil
		}
		var buf = &bytes.Buffer{}
		// 排序
		sort.Slice(pkts, func(i, j int) bool {
			return pkts[i].SequenceNumber < pkts[j].SequenceNumber
		})
		for _, pkt := range pkts {
			var naltype = pkt.Payload[0] & 0x1f
			if naltype >= 0 && naltype <= 23 {
				// Single NAL
				buf.Write([]byte{0, 0, 0, 1})
				buf.Write(pkt.Payload)
			} else if naltype == 28 {
				// FU-A NAL
				var fuIndicator = pkt.Payload[0]
				var fuHeader = pkt.Payload[1]
				var nalHeader = (fuIndicator & 0xe0) | (fuHeader & 0x1f)
				if fuHeader&0x80 != 0 {
					buf.Write([]byte{0, 0, 0, 1, nalHeader})
				}
				buf.Write(pkt.Payload[2:])
			} else if naltype == 24 {
				// STAP-A NAL
				var offset = 1
				for offset < len(pkt.Payload) {
					var size = int(binary.BigEndian.Uint16(pkt.Payload[offset : offset+2]))
					offset = offset + 2
					var nextNalType = pkt.Payload[offset] & 0x1f
					util.Warnf("STAP-A has naltype = %d, size = %d", nextNalType, size)
					if offset+size > len(pkt.Payload) {
						break
					}
					buf.Write([]byte{0, 0, 0, 1})
					buf.Write(pkt.Payload[offset : offset+size])
					offset += size
				}
			}
		}
		return &prtp.Packet{
			Header:  pkts[0].Header,
			Payload: buf.Bytes(),
		}
	}
	return nil
}
```

**Comment by yapingcat** [comment]
确认几个问题
1. NewRtpUDPStream 的回调函数，只有视频数据吗？
2. 裸码流 oldPkt.Payload 写入本地文件，ffplay能否播放？
3. 下面这行代码，能否处理sequence 回滚的情况
```
sort.Slice(pkts, func(i, j int) bool {
			return pkts[i].SequenceNumber < pkts[j].SequenceNumber
		})
```

**Comment by xiaokuang95** [comment]
> 确认几个问题
> 
> 1. NewRtpUDPStream 的回调函数，只有视频数据吗？
> 2. 裸码流 oldPkt.Payload 写入本地文件，ffplay能否播放？
> 3. 下面这行代码，能否处理sequence 回滚的情况
> 
> ```
> sort.Slice(pkts, func(i, j int) bool {
> 			return pkts[i].SequenceNumber < pkts[j].SequenceNumber
> 		})
> ```

1 NewRtpUDPStream 我是用ffmpeg推送的h264码流
2 保存的文件，用ffplay是能正常播放视频的
3 我是根据timestamp和mark来判断是否是一个完整的帧，然后进行排序，进行解包

**Comment by xiaokuang95** [comment]
> > 确认几个问题
> > 
> > 1. NewRtpUDPStream 的回调函数，只有视频数据吗？
> > 2. 裸码流 oldPkt.Payload 写入本地文件，ffplay能否播放？
> > 3. 下面这行代码，能否处理sequence 回滚的情况
> > 
> > ```
> > sort.Slice(pkts, func(i, j int) bool {
> > 			return pkts[i].SequenceNumber < pkts[j].SequenceNumber
> > 		})
> > ```
> 
> 1 NewRtpUDPStream 我是用ffmpeg推送的h264码流 2 保存的文件，用ffplay是能正常播放视频的 3 我是根据timestamp和mark来判断是否是一个完整的帧，然后进行排序，进行解包

这是ffmpeg 推流的命令 ffmpeg -re -i .\tmp.264 -vcodec copy -f rtp rtp://192.168.0.168:6666

**Comment by yapingcat** [comment]
> > > 确认几个问题
> > > 
> > > 1. NewRtpUDPStream 的回调函数，只有视频数据吗？
> > > 2. 裸码流 oldPkt.Payload 写入本地文件，ffplay能否播放？
> > > 3. 下面这行代码，能否处理sequence 回滚的情况
> > > 
> > > ```
> > > sort.Slice(pkts, func(i, j int) bool {
> > > 			return pkts[i].SequenceNumber < pkts[j].SequenceNumber
> > > 		})
> > > ```
> > 
> > 
> > 1 NewRtpUDPStream 我是用ffmpeg推送的h264码流 2 保存的文件，用ffplay是能正常播放视频的 3 我是根据timestamp和mark来判断是否是一个完整的帧，然后进行排序，进行解包
> 
> 这是ffmpeg 推流的命令 ffmpeg -re -i .\tmp.264 -vcodec copy -f rtp rtp://192.168.0.168:6666

方便提供一下 tmp.h264吗？我复现看看

**Comment by xiaokuang95** [comment]
> 
文件超过25mb好像无法上传到github了

**Comment by xiaokuang95** [comment]
> ffmpeg 发的rtp流时间戳都是一样的... oldPkt.Timestamp 用time.Now().UnixMilli()代替测试，我这边本地测试已经正常了
> 
> ```go
> err := publishClient.GetRtmpClient().WriteVideo(codec.CODECID_VIDEO_H264, oldPkt.Payload, oldPkt.Timestamp, oldPkt.Timestamp)
> 		if err != nil {
> 			util.Errorf(err.Error())
> 		}
> ```

如果是本地的时间戳，那么音频和视频是不是就会造成不同步的情况

**Comment by yapingcat** [comment]
> > ffmpeg 发的rtp流时间戳都是一样的... oldPkt.Timestamp 用time.Now().UnixMilli()代替测试，我这边本地测试已经正常了
> > ```go
> > err := publishClient.GetRtmpClient().WriteVideo(codec.CODECID_VIDEO_H264, oldPkt.Payload, oldPkt.Timestamp, oldPkt.Timestamp)
> > 		if err != nil {
> > 			util.Errorf(err.Error())
> > 		}
> > ```
> 
> 如果是本地的时间戳，那么音频和视频是不是就会造成不同步的情况

网络抖了，应该就会有影响
