### ISSUE TITLE
Fragment格式的mp4入参是否可以由WriteSeeker改为Writer

### ISSUE THREAD

**Issue by autoexpect** [yapingcat/gomedia#67]
fmp4协议上支持从头到尾不用seek的格式，不知道是否可以这样做。

**Comment by yapingcat** [comment]
理论上是这样的，但是golang 没有类似 c/c++ 中的tell 函数，tell函数的能力在golang被集成到Seek 接口里面了

**Comment by autoexpect** [comment]
fmp4模式发现Seek的都0，所以定义一个Wraper包一下可以解决
