### ISSUE TITLE
使用时的偶现bug

### ISSUE THREAD

**Issue by zxs943023403** [yapingcat/gomedia#68]
拉流服务链接的时候，偶尔会出现bug：
panic: interface conversion: interface {} is uint8, not bool

goroutine 6 [running]:
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).handlePlay(0xc0000d2200, {0xc00046a067, 0x7f10a98f75d0, 0x2c})
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:392 +0x5f9
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).handleCommand(0xc0000d2200, {0xc00046a060, 0x2c, 0x2c})
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:322 +0xf8
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).handleMessage(0x4ff3a0, 0x48ca01)
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:294 +0x1a7
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).Input.func1(0x48c9fe)
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:200 +0x2b
github.com/yapingcat/gomedia/go-rtmp.(*chunkStreamReader).readRtmpMessage(0xc0000b40c0, {0xc00005e000, 0xc000036400, 0xc00005e000}, 0xc000085f28)
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/chunk.go:373 +0x3db
github.com/yapingcat/gomedia/go-rtmp.(*RtmpServerHandle).Input(0xc0000d2200, {0xc00005e000, 0xc00002ff90, 0x4df16d})
        /gopath/pkg/mod/github.com/yapingcat/gomedia@v0.0.0-20230222121919-c67df405bf33/go-rtmp/server.go:198 +0x13d

**Comment by zxs943023403** [comment]
是使用的时候有问题吗？

**Comment by yapingcat** [comment]
方便 提供一下抓包吗？
看这个错误，应该是协议层面的问题

**Comment by yapingcat** [comment]
我明白了，你当前使用的版本不是最新的版本，麻烦更新到最新版本测试看看

这个问题和 https://github.com/yapingcat/gomedia/issues/56 类似，应该是解决过了
