### ISSUE TITLE
panic in GetSyncTable

### ISSUE THREAD

**Issue by fastfading** [yapingcat/gomedia#71]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/8351732/234164866-29d4bbcc-dc6d-42ff-bb54-dcbaa89bdd89.png">
in some mp4 , this value is nil .
mp4 is small, generated by ffmepg.

https://user-images.githubusercontent.com/8351732/234164974-b92ef45f-9267-48e5-ae1d-075675e5c24e.mp4

<img width="687" alt="image" src="https://user-images.githubusercontent.com/8351732/234165079-684c53ce-4642-4e05-8aa7-0aeb5a47173e.png">

**Comment by yapingcat** [comment]
there is no **stss** box  in  mp4 file

**Comment by fastfading** [comment]
I see ，  why is that ？   because it is too short ？
generate code are like below
cmd := FFMPEG_PATH + ` -i ` + NoContentImgPath + ` -f lavfi -i anullsrc=r=32000:cl=mono -t ` + strconv.FormatFloat(duration, 'f', 2, 64) +
		` -s 1280x720 -vcodec libx264  -acodec aac -preset veryfast -r 25 -g 750 -movflags +faststart ` + mergeMp4Path

**Comment by fastfading** [comment]
I try regenerate the mp4 with ffmpeg,  the same issue accur.
ffmpeg -i huadong.mp4 new.mp4

**Comment by fastfading** [comment]
thanks, it is the root cause indeed
