### ISSUE TITLE
ts文件转mp4，acc音频转换失败

### ISSUE THREAD

**Issue by heyunping** [yapingcat/gomedia#72]
![image](https://user-images.githubusercontent.com/82068365/234236861-8e6d6adb-dc74-4fb9-9d10-b7e879b9e818.png)
ts文件转mp4，acc音频转换失败，是什么问题呢

**Comment by yapingcat** [comment]
需要提供一下 ts文件

**Comment by heyunping** [comment]
麻烦了，这是ts文件




吖头丶你好傻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] ts文件转mp4，acc音频转换失败 (Issue #72)





 
需要提供一下 ts文件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

00001.ts (6.79M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0f6237399d5ff59a3470f1501f33544a4a16035d095155511f53065d081e5e55575b1a5f000b5448010601010d0455500b06540a393b665502520708174715650f&t=exs_ftn_download&code=2b7993fe




00002.ts (6.55M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0a3163320d21a59d3123a55b1762004d4f455053555406571a54000b084f560053054e070355034f0e5252540203040455575402316a3252070153001f1641620a&t=exs_ftn_download&code=71c21b2b

**Comment by heyunping** [comment]
还有个问题，为什么不实现h265类型转mp4呢

**Comment by heyunping** [comment]
![image](https://user-images.githubusercontent.com/82068365/234450145-1b7bb658-8915-460a-b56e-4a0576677e1c.png)
我这样写，合成出来的视频是黑屏

**Comment by heyunping** [comment]
![image](https://user-images.githubusercontent.com/82068365/234454677-2455d20f-2c5e-4973-b454-1b30d5120a43.png)
这里越界也是ts文件不标准的原因吗

**Comment by yapingcat** [comment]
这个越界表示track没有写入音频或者视频数据数据

**Comment by yapingcat** [comment]
可以参考[ ts_to_mp4](https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go)的写法
确保有对应的frame在AddTrack

**Comment by yapingcat** [comment]
3870314 已经增加了越界保护，可以更新测试看看

**Comment by heyunping** [comment]
谢谢，帮大忙了
&nbsp;


吖头丶你好傻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月26日(星期三) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yapingcat/gomedia] ts文件转mp4，acc音频转换失败 (Issue #72)





 
3870314 已经增加了越界保护，可以更新测试看看
