### ISSUE TITLE
Multiple audio playback errors after converting TS to MP4

### ISSUE THREAD

**Issue by xypwn** [yapingcat/gomedia#75]
Hey, first of all thanks a lot for the library! I love the idea of being able to mux different media codecs in native go.

So, I am not 100% sure that this happens because of this library, but it worked just fine using FFmpeg, so I think it may have something to do with it.

I used your [convert ts to mp4 example](https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go) with some slight adaptations in my code.

Basically, MPV plays mostly fine, but emits lots of audio-related errors, while VLC just cuts out parts of the audio. When playing the raw TS file with MPV, I don't get any errors. The video also seems 100% OK.

Here is an excerpt of the errors generated when playing with MPV:

```
[ffmpeg/audio] aac: Input buffer exhausted before END element found
Error decoding audio.
AV: 00:00:11 / 00:21:59 (1%) A-V:  0.000
[ffmpeg/audio] aac: Input buffer exhausted before END element found
Error decoding audio.
AV: 00:00:29 / 00:21:59 (2%) A-V:  0.000
[ffmpeg/audio] aac: Number of bands (48) exceeds limit (43).
Error decoding audio.
AV: 00:00:31 / 00:21:59 (2%) A-V: -0.009 ct:  0.053
Invalid video timestamp: 32.032000 -> 32.032000
AV: 00:00:37 / 00:21:59 (3%) A-V:  0.000
[ffmpeg/audio] aac: Input buffer exhausted before END element found
Error decoding audio.
AV: 00:00:43 / 00:21:59 (3%) A-V:  0.000 ct:  0.065
[ffmpeg/audio] aac: invalid band type
Error decoding audio.
```

Here the code:
```go
func tsToMP4(tsInput io.Reader, mp4Output io.WriteSeeker) error {
	const errPfx = "sp: tsToMP4(): "

	muxer, err := mp4.CreateMp4Muxer(mp4Output)
	if err != nil {
		return errors.New(errPfx + err.Error())
	}

	var writeError error

	// https://github.com/yapingcat/gomedia/blob/main/example/example_convert_ts_to_mp4.go
	hasAudio := false
	hasVideo := false
	var atid uint32 = 0
	var vtid uint32 = 0
	demuxer := mpeg2.NewTSDemuxer()
	demuxer.OnFrame = func(cid mpeg2.TS_STREAM_TYPE, frame []byte, pts uint64, dts uint64) {
		if cid == mpeg2.TS_STREAM_H264 {
			if !hasVideo {
				vtid = muxer.AddVideoTrack(mp4.MP4_CODEC_H264)
				hasVideo = true
			}
			err := muxer.Write(vtid, frame, uint64(pts), uint64(dts))
			if err != nil {
				writeError = err
			}
		} else if cid == mpeg2.TS_STREAM_AAC {
			if !hasAudio {
				atid = muxer.AddAudioTrack(mp4.MP4_CODEC_AAC)
				hasAudio = true
			}
			err = muxer.Write(atid, frame, uint64(pts), uint64(dts))
			if err != nil {
				writeError = err
			}
		} else if cid == mpeg2.TS_STREAM_AUDIO_MPEG1 || cid == mpeg2.TS_STREAM_AUDIO_MPEG2 {
			if !hasAudio {
				atid = muxer.AddAudioTrack(mp4.MP4_CODEC_MP3)
				hasAudio = true
			}
			err := muxer.Write(atid, frame, uint64(pts), uint64(dts))
			if err != nil {
				writeError = err
			}
		}
	}

	if err := demuxer.Input(tsInput); err != nil {
		return errors.New(errPfx + err.Error())
	}

	muxer.WriteTrailer()

	if writeError != nil {
		// Currently only propagates last error
		return errors.New(errPfx + "mp4 muxer: " + writeError.Error())
	}

	return nil
}
```

Please be sure to let me know if you need any more info, since I can't really estimate what else could be relevant here.

**Comment by yapingcat** [comment]
i need ts file

**Comment by xypwn** [comment]
Thanks for your quick response! I have attached a shortened version of a file that still gets many of these errors. In this case, I even used your example program for conversion to MP4.
Another thing I noticed is that I get an "unexpected EOF" error; I'd appreciate if you could examine that too.
[example.zip](https://github.com/yapingcat/gomedia/files/11427722/example.zip)

**Comment by yapingcat** [comment]
it works well on my windows pc. This mp4 file plays normally with vlc, ffpay, mpv 

> Another thing I noticed is that I get an "unexpected EOF" error; I'd appreciate if you could examine that too.
that means ts file is not completed, you can skip this error ,in most case

**Comment by yapingcat** [comment]
i play mp4 with this command  ` .\mpv.exe -v --log-file=play.log .\1.mp4`, but I didn't find any errors in this log file

**Comment by xypwn** [comment]
Are you sure you played the whole file?
I got this with FFPlay (and its equivalent with MPV since it uses libffmpeg)
```
[aac @ 0x7f0d6c0780c0] invalid band typeq=  590KB sq=    0B f=0/0   
[aac @ 0x7f0d6c0780c0] Number of bands (45) exceeds limit (40)./0   
[aac @ 0x7f0d6c0780c0] Number of bands (45) exceeds limit (40)./0   
[aac @ 0x7f0d6c0780c0] Number of bands (62) exceeds limit (40)./0   
[aac @ 0x7f0d6c0780c0] Number of bands (60) exceeds limit (40)./0   
[aac @ 0x7f0d6c0780c0] Number of bands (51) exceeds limit (40)./0   
[aac @ 0x7f0d6c0780c0] Gain control is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 0x7f0d6c0780c0] channel element 2.4 is not allocated
```

The issue with VLC cutting out isn't really present in this sample, but it seems to be related to these types of errors.

**Comment by yapingcat** [comment]
i got the same error, thank you

**Comment by xypwn** [comment]
Here's my version of play.log btw, if you need it
[play.log](https://github.com/yapingcat/gomedia/files/11428224/play.log)

**Comment by yapingcat** [comment]
There are some garbage bytes in ts file 
![image](https://github.com/yapingcat/gomedia/assets/32125710/5b120acd-29b9-459a-b653-5773d7c6fa5c)

please update gomedia to latest version. The latest version of gomedia supports this case

**Comment by xypwn** [comment]
It works! I can now play the mp4 file on VLC and MPV without errors or cutouts.
Thanks a lot for taking the time to figure all this out!
