### ISSUE TITLE
mpeg2: invalid output audio stream when muxing h264 and aac

### ISSUE THREAD

**Issue by iMro0t** [yapingcat/gomedia#76]
I have raw h264 and aac files ([sample.zip](https://github.com/yapingcat/gomedia/files/11451923/sample.zip)). I am trying to mux it into mpegts. This is the example code

## sample code 
```go
package main

import (
	"github.com/yapingcat/gomedia/go-mpeg2"
	"os"
)

func main() {
	muxer := mpeg2.NewTSMuxer()
	vid := muxer.AddStream(mpeg2.TS_STREAM_H264)
	aid := muxer.AddStream(mpeg2.TS_STREAM_AAC)

	out, _ := os.OpenFile("out.ts", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	defer out.Close()
	muxer.OnPacket = func(pkg []byte) {
		out.Write(pkg)
	}

	h264Bytes, _ := os.ReadFile("h264")
	muxer.Write(vid, h264Bytes, 0, 0)

	aacBytes, _ := os.ReadFile("aac")
	muxer.Write(aid, aacBytes, 0, 0)
}
```

### here aac is missing sample rate and other information

```bash
❯ ffprobe -hide_banner out.ts
[mpegts @ 0x13e604ca0] start time for stream 1 is not set in estimate_timings_from_pts
[mpegts @ 0x13e604ca0] stream 1 : no TS found at start of file, duration not set
[mpegts @ 0x13e604ca0] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mpegts, from 'out.ts':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 632845 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 0 channels
```

## valid result with different order

```go
aacBytes, _ := os.ReadFile("aac")
muxer.Write(aid, aacBytes, 0, 0)

h264Bytes, _ := os.ReadFile("h264")
muxer.Write(vid, h264Bytes, 0, 0)
```

```bash
❯ ffprobe -hide_banner out.ts
Input #0, mpegts, from 'out.ts':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 632845 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 64 kb/s
```

**Comment by yapingcat** [comment]
you should split h264/aac frame 

refer [mux_ts_aac](https://github.com/yapingcat/gomedia/blob/main/example/example_mux_ts_aac.go) split aac frame

refer [mux_ts_h264](https://github.com/yapingcat/gomedia/blob/main/example/example_mux_ts.go) split h264 frame

**Comment by yapingcat** [comment]
**audio and video frame should be written alternately. just like code below**

```golang
package main

import (
	"fmt"
	"os"

	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {
	muxer := mpeg2.NewTSMuxer()
	vid := muxer.AddStream(mpeg2.TS_STREAM_H264)
	aid := muxer.AddStream(mpeg2.TS_STREAM_AAC)

	out, _ := os.OpenFile("out.ts", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	defer out.Close()
	muxer.OnPacket = func(pkg []byte) {
		out.Write(pkg)
	}

	var pts uint64 = 0
	var dts uint64 = 0

	notify_write_auido := make(chan struct{}, 1)
	notify_write_video := make(chan struct{}, 1)

	done_video := make(chan struct{})
	done_audio := make(chan struct{})
	go func() {
		h264Bytes, _ := os.ReadFile("h264")
		codec.SplitFrameWithStartCode(h264Bytes, func(nalu []byte) bool {
			pts += 40
			dts += 40
			muxer.Write(vid, nalu, pts, dts)
			notify_write_auido <- struct{}{}
			<-notify_write_video
			return true
		})
		close(done_video)
	}()

	go func() {
		aacSampleRate := -1
		aacBytes, _ := os.ReadFile("aac")
		codec.SplitAACFrame(aacBytes, func(aac []byte) {
			if aacSampleRate == -1 {
				adts := codec.NewAdtsFrameHeader()
				adts.Decode(aac)
				aacSampleRate = codec.AACSampleIdxToSample(int(adts.Fix_Header.Sampling_frequency_index))
				fmt.Println(aacSampleRate)
			}
			<-notify_write_auido
			muxer.Write(aid, aac, pts, pts)
			pts += uint64(1024 * 1000 / aacSampleRate)
			notify_write_video <- struct{}{}
		})
		close(done_audio)
	}()

	select {
	case <-done_audio:
		break
	case <-done_video:
		break
	}
}
```

**Comment by iMro0t** [comment]
@yapingcat Thanks for explanation. this was super useful information. i didn't know that we should write video/audio frames alternatively. i would like to know that is this necessary for multi track mpegts? also what would be efficient way to write mpegts for HLS?

**Comment by yapingcat** [comment]
> Thanks for explanation. this was super useful information. i didn't know that we should write video/audio frames alternatively. i would like to know that is this necessary for multi track mpegts? also what would be efficient way to write mpegts for HLS?

in this case，the best way is that  you should  write video/audio frames alternatively .
in fact，ffmpeg probe the ts stream to get video/audio frame，because ffmpeg need codec parameter to init  audio/video encoder. 

> Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

this ffmpeg log show us, we can set probe distance.

> also what would be efficient way to write mpegts for HLS?

1. when you convert media stream(just like rtsp,rtmp,webrtc  ....) to hls,you can take  the receiving order as the write order,
    recv one frame and then write mpegts 
2. If your scenario is like this issue，Audio and video are separate. It will be complicated.
