### ISSUE TITLE
处理不标准的ts文件

### ISSUE THREAD

**Issue by heyunping** [yapingcat/gomedia#77]
一个ts文件，使用ffmpeg能够转MP4，但是贵库报错“len of data < Adaptation_field_length”，请问能否适配一下

**Comment by yapingcat** [comment]
> 一个ts文件，使用ffmpeg能够转MP4，但是贵库报错“len of data < Adaptation_field_length”，请问能否适配一下

还是上一个问题吗？同一个ts文件？

**Comment by heyunping** [comment]
不是同一个，见附件




吖头丶你好傻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] 处理不标准的ts文件 (Issue #77)





  
一个ts文件，使用ffmpeg能够转MP4，但是贵库报错“len of data < Adaptation_field_length”，请问能否适配一下
  
还是上一个问题吗？同一个ts文件？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

00001.ts (3.54M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5e393738755df5c8652bf151133500181b4d070d5353070e4e0f520e011856525a5f1a0f0d01561a525f005e57560700515b0e59353d3207530907091b4141375e&t=exs_ftn_download&code=c9785527

**Comment by yapingcat** [comment]
请更新到最新版本在测试一下

参考了VLC的实现，修复了一个bug和做了一些兼容处理，不确定能是否能处理所有的场景，可以帮忙多测试，看是否还有问题，感谢

**Comment by heyunping** [comment]
我已经拉取最新代码调试，发现能够转换成功，但是转换后的mp4文件出现音画不同步，视频似乎有1.5倍速，音频为正常速度，两分钟的视频播放到1分30秒左右就卡住，音频则为正常速度播放至2分钟，转换后的MP4见附件




吖头丶你好傻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月16日(星期二) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] 处理不标准的ts文件 (Issue #77)





 
请更新到最新版本在测试一下
 
参考了VLC的实现，修复了一个bug和做了一些兼容处理，不确定能是否能处理所有的场景，可以帮忙多测试，看是否还有问题，感谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

202305101032-202305101152.mp4 (3.32M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=66656339f585f9cf3277a5504265011f4c115a5c0500010619505a0f0648025504554e0b5252011d0356055f075703530152055c647833020457500951540301045651145655010304505209555406021a08130d6458&t=exs_ftn_download&code=4ec9de30

**Comment by yapingcat** [comment]
应该是正常的，这个ts文件他的音频的duration要大于视频的，在1分30秒之后都是音频帧。ts播放看起来也是音画不同步的，视频也是有加速

用vlc 播放可以看出差别
播放ts
![image](https://github.com/yapingcat/gomedia/assets/32125710/b8ee867e-09c6-4bf8-9a86-7a28aa69429c)

播放MP4
![image](https://github.com/yapingcat/gomedia/assets/32125710/5cc5f762-c53b-49c4-acea-7f7cbeaa9f1d)


两者duration不一样

**Comment by heyunping** [comment]
finish

**Comment by heyunping** [comment]
你好，如果我想ts合并转码为mp4文件时，将ts文件进行剪切，就是不一定是将完整的ts转码为mp4，而是只取其中一段时间，应该从哪里改造呢




吖头丶你好傻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yapingcat/gomedia"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yapingcat/gomedia] 处理不标准的ts文件 (Issue #77)





 
应该是正常的，这个ts文件他的音频的duration要大于视频的，在1分30秒之后都是音频帧。ts播放看起来也是音画不同步的，视频也是有加速
 
用vlc 播放可以看出差别
 播放ts
 
 
播放MP4
 
 
两者duration不一样
