### ISSUE TITLE
[h264 @ 0x14fe04ba0] concealing 1020 DC, 1020 AC, 1020 MV errors in I frame

### ISSUE THREAD

**Issue by iMro0t** [yapingcat/gomedia#79]
## i am trying to convert mp4 to mpegts but getting following error in ffprobe

```bash
❯ ffprobe -hide_banner out.ts
[h264 @ 0x14c704b40] concealing 1020 DC, 1020 AC, 1020 MV errors in I frame
Input #0, mpegts, from 'out.ts':
  Duration: 00:00:08.04, start: 46693.362289, bitrate: 980 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn

```

## sample mp4
[v.mp4.zip](https://github.com/yapingcat/gomedia/files/11585509/v.mp4.zip)

## here is the sample code
i suspect it's causing due to `codec.SplitFrameWithStartCode` because if we remove splitting and directly use `muxer.Write(vid, nalu, pkt.Pts, pkt.Dts)` then its working fine but it's causing weird problem after using this mpegts in hls stream
```go
package main

import (
	"fmt"
	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-mp4"
	"os"

	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {
	muxer := mpeg2.NewTSMuxer()
	vid := muxer.AddStream(mpeg2.TS_STREAM_H264)

	out, _ := os.OpenFile("out.ts", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	defer out.Close()
	muxer.OnPacket = func(pkg []byte) {
		out.Write(pkg)
	}

	f, err := os.Open("v.mp4")
	if err != nil {
		panic(err)
	}
	demuxer := mp4.CreateMp4Demuxer(f)
	_, err = demuxer.ReadHead()
	if err != nil {
		panic(err)
	}

	for {
		pkt, err := demuxer.ReadPacket()
		if err != nil {
			fmt.Println(err)
			break
		}
		codec.SplitFrameWithStartCode(pkt.Data, func(nalu []byte) bool {
			muxer.Write(vid, nalu, pkt.Pts, pkt.Dts)
			return true
		})
	}
}

```

**Comment by yapingcat** [comment]
> ## i am trying to convert mp4 to mpegts but getting following error in ffprobe
> ```shell
> ❯ ffprobe -hide_banner out.ts
> [h264 @ 0x14c704b40] concealing 1020 DC, 1020 AC, 1020 MV errors in I frame
> Input #0, mpegts, from 'out.ts':
>   Duration: 00:00:08.04, start: 46693.362289, bitrate: 980 kb/s
>   Program 1 
>   Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
> ```
> 
> ## sample mp4
> [v.mp4.zip](https://github.com/yapingcat/gomedia/files/11585509/v.mp4.zip)
> 
> ## here is the sample code
> i suspect it's causing due to `codec.SplitFrameWithStartCode` because if we remove splitting and directly use `muxer.Write(vid, nalu, pkt.Pts, pkt.Dts)` then its working fine but it's causing weird problem after using this mpegts in hls stream
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/yapingcat/gomedia/go-codec"
> 	"github.com/yapingcat/gomedia/go-mp4"
> 	"os"
> 
> 	"github.com/yapingcat/gomedia/go-mpeg2"
> )
> 
> func main() {
> 	muxer := mpeg2.NewTSMuxer()
> 	vid := muxer.AddStream(mpeg2.TS_STREAM_H264)
> 
> 	out, _ := os.OpenFile("out.ts", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
> 	defer out.Close()
> 	muxer.OnPacket = func(pkg []byte) {
> 		out.Write(pkg)
> 	}
> 
> 	f, err := os.Open("v.mp4")
> 	if err != nil {
> 		panic(err)
> 	}
> 	demuxer := mp4.CreateMp4Demuxer(f)
> 	_, err = demuxer.ReadHead()
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	for {
> 		pkt, err := demuxer.ReadPacket()
> 		if err != nil {
> 			fmt.Println(err)
> 			break
> 		}
> 		codec.SplitFrameWithStartCode(pkt.Data, func(nalu []byte) bool {
> 			muxer.Write(vid, nalu, pkt.Pts, pkt.Dts)
> 			return true
> 		})
> 	}
> }
> ```

in this mp4 file, h264 frame has been  encoded in multi slice 

please test  with the following code

```golang
package main

import (
	"fmt"
	"github.com/yapingcat/gomedia/go-codec"
	"github.com/yapingcat/gomedia/go-mp4"
	"os"

	"github.com/yapingcat/gomedia/go-mpeg2"
)

func main() {
	muxer := mpeg2.NewTSMuxer()
	vid := muxer.AddStream(mpeg2.TS_STREAM_H264)

	out, _ := os.OpenFile("out.ts", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	defer out.Close()
	muxer.OnPacket = func(pkg []byte) {
		out.Write(pkg)
	}

	f, err := os.Open("v.mp4")
	if err != nil {
		panic(err)
	}
	demuxer := mp4.CreateMp4Demuxer(f)
	_, err = demuxer.ReadHead()
	if err != nil {
		panic(err)
	}

	for {
		pkt, err := demuxer.ReadPacket()
		if err != nil {
			fmt.Println(err)
			break
		}
                muxer.Write(vid, pkt.Data, pkt.Pts, pkt.Dts)
		//codec.SplitFrameWithStartCode(pkt.Data, func(nalu []byte) bool {
		//	muxer.Write(vid, nalu, pkt.Pts, pkt.Dts)
		//	return true
		//})
	}
}

```

**Comment by iMro0t** [comment]
@yapingcat it seems minor issue 
```bash
[hls @ 0x126e17a10] Skip ('#EXT-X-VERSION:3')
[hls @ 0x126e17a10] Opening 'http://192.168.1.9:8181/dec-71.ts' for reading
[hls @ 0x126e17a10] Opening 'http://192.168.1.9:8181/dec-72.ts' for reading
[http @ 0x128834e00] Opening 'http://192.168.1.9:8181/dec-73.ts' for reading
[hls @ 0x126e17a10] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, hls, from 'http://192.168.1.9:8181/master.m3u8':
```

not every time but ffplay gives this error randomly

closing this for now since its not related
