### ISSUE TITLE
multiple calls of Movmuxer.writeMoov panics

### ISSUE THREAD

**Issue by iMro0t** [yapingcat/gomedia#86]
call chain `Movmuxer.writeMoov -> makeTrak -> ... -> makeStsd -> h264ExtraData.export -> codec.CreateH264AVCCExtradata`

codec.CreateH264AVCCExtradata function is modifying the original slice `spss` and `ppss`

https://github.com/yapingcat/gomedia/blob/bc994fea6ee06fc4bd4711e04658f268ab0b2c52/go-codec/h264.go#L307-L358

**Comment by yapingcat** [comment]
sorry. i can't get the point of ’multiple calls‘,  In which scenario, writeMoov is called multiple times?

**Comment by iMro0t** [comment]
in my case i was writing init segment with `Movmuxer.WriteInitSegment` function in different file and then `Movmuxer.Write` is internally calling  `Movmuxer.writeMoov`

**Comment by yapingcat** [comment]
in your case ,fmp4 is used for hls ? and  do you create  mov muxer with MP4_FLAG_FRAGMENT ?

if you  use MP4_FLAG_FRAGMENT , you should not call the  WriteInitSegment function.mp4 library  write moov box Automatically

**Comment by iMro0t** [comment]
> in your case ,fmp4 is used for hls ?

Yes

> do you create mov muxer with MP4_FLAG_FRAGMENT ?

Yes

>  mp4 library write moov box Automatically

it writes moov box but its only writing in first segment. maybe in this case OnFragment callback will be helpful so on first OnFragment callback we can save it to init fragment and rest is for fmp4

**Comment by yapingcat** [comment]
you should use MP4_FLAG_DASH flag  for hls. refer to (hls fmp4)[https://github.com/yapingcat/gomedia/blob/main/example/example_convert_flv_to_hls_fmp4.go]
for hls,the best way is save moov box in (EXT-X-MAP)[https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.5], write moov in every segment is unnecessary

**Comment by iMro0t** [comment]
https://github.com/yapingcat/gomedia/blob/bc994fea6ee06fc4bd4711e04658f268ab0b2c52/example/example_convert_flv_to_hls_fmp4.go#L78-L83

the example code also calls muxer.WriteInitSegment which may lead to this error too

**Comment by yapingcat** [comment]
`muxer, err = mp4.CreateMp4Muxer(mp4file, mp4.WithMp4Flag(mp4.MP4_FLAG_DASH))`

if mp4 muxer is created with MP4_FLAG_DASH , the `writeMoov ` function  will not  been called in mp4 library.
