### ISSUE TITLE
rtsp-client 无法处理rtsp 301重定向消息

### ISSUE THREAD

**Issue by xiaoxiaodetian** [yapingcat/gomedia#89]
rtsp-client 发送optinons， 收到301 重定向消息后，没有去请求重定向后的rtsp地址，二是继续发送describe消息

**Comment by yapingcat** [comment]
> rtsp-client 发送optinons， 收到301 重定向消息后，没有去请求重定向后的rtsp地址，二是继续发送describe消息

是的，rtsp 库只处理协议相关的，网络相关由调用者自身来管理和维护

**Comment by yapingcat** [comment]
在HandleOption 处理 301 的情况，可以根据重定向的url 创建新rtsp 句柄。用新的rtsp句柄来走rtsp的流程，这样处理应该会比较简单
