### ISSUE TITLE
unsupport empty aggregate control url in session level descriptions

### ISSUE THREAD

**Issue by simman** [yapingcat/gomedia#96]
版本: `github.com/yapingcat/gomedia v0.0.0-20230905155010-55b9713fcec1 // indirect`

使用的 `example_rtsp_client_rtp_over_udp.go` ，然后用的obs + lal 做服务端；

报错：

https://github.com/yapingcat/gomedia/blob/55b9713fcec1acb9eda29e137effc81f6bf17ed5/go-rtsp/rtsp-client.go#L435-L437

好像走不到 216 行吧？

https://github.com/yapingcat/gomedia/blob/55b9713fcec1acb9eda29e137effc81f6bf17ed5/go-rtsp/sdp/sdp.go#L215-L219

**Comment by yapingcat** [comment]
> 好像走不到 216 行吧？
> 
> https://github.com/yapingcat/gomedia/blob/55b9713fcec1acb9eda29e137effc81f6bf17ed5/go-rtsp/sdp/sdp.go#L215-L219

这个逻辑代表的是获取session level的control url.  大多数情况下的rtsp sdp 里面都应该会有session level 的control url

**Comment by simman** [comment]
的确没有，我自己做了个兼容。
